pkg/webhook/webhook.go
Updated the validating webhook configuration to have an owner reference to the fleet-system namespace. 
Fixes #345 
I have:
TBA
=> feat: Added ownerRef to agent created webhook config.

.github/workflows/trivy.yml, pkg/controllers/work/apply_controller_helper_test.go, pkg/controllers/work/apply_controller_integration_test.go, pkg/controllers/work/patch_util.go
Do not return an error if someone removes the last applied annotation in the applied resources. The three way merge lib can handle this case.
Fixes # 349
I have:
IT
=> fix: relax the case for last applied annotation is removed

charts/member-agent/templates/deployment.yaml, charts/member-agent/values.yaml, cmd/memberagent/main.go
Provide an solution for community to support CA auth
I have:
- Kind Cluster e2e workflow on README is verified working, no existing workflow get affected.
- Integ test is performed in LinkedIn environment
- Helm yaml generation is verified
```
The default behavior has no changes.
For the yamls with CA info enabled
==================================================
helm template member-agent ./charts/member-agent/ \
--set useCAAuth=true \
--set config.identityKey="identity-key-path" \
--set config.identityCert="identity-cert-path" \
--set config.CABundle="ca-bundle-path" \
--set config.hubURL=hub-cluster-api-url \
--set image.repository=member-agent-image-url \
--set image.tag=0.0.1 \
--set refreshtoken.repository=refresh-token-url \
--set refreshtoken.tag=0.0.1 \
--set …
```
=> feat: support CA bundle and identity cert/key authentication

cmd/authtoken/main.go, cmd/authtoken/main_test.go, pkg/authtoken/providers/azure/azure_msi.go
Today the Azure provider are using a static scope in token. In future the different scope need to be used for the flexible scenario. 
This changes are:
1. add a new `--scope` arguments in refresh-token. The new scope argument will be pass to Azure token provider. 
3. For the backward compatibility, the scope argument is optional. The old static scope will be used by default. 
I have:
I added unit test for changes codes
=> feat: a new "scope" argument for refresh-token

cmd/memberagent/main.go, cmd/memberagent/main_test.go, cmd/memberagent/testdata/token
When member agent use secure TLS talk to hub, it  use either a specified CA bundle or CA data in configuration. This changes to allow member agent use OS's [root certificate](https://go.dev/src/crypto/x509/root_linux.go). 
The changes are:
1. refactor the codes of building hub's kubeconfig
2. It is not mandatory to specify CA data or CA bundle in arguments
I have:
=> feat: allow member agent use OS's root certificate authority

cmd/memberagent/main.go, cmd/memberagent/main_test.go
This is following up some comments on another PR: #364 after PR merged. 
I have:
=> feat: allow member agent use OS's root certificate authority (follow up)

pkg/scheduler/framework/cyclestate.go, pkg/scheduler/framework/cyclestate_test.go
It features the the cycle state struct which the scheduler and its plugins use to keep states.
I have:
Some fields are commented out as they are unused in this split PR; will uncomment in a following PR.
=> feat: scheduler (3/): add cycle state implementation

pkg/scheduler/framework/score.go, pkg/scheduler/framework/score_test.go
It features some structs for keeping scores in the scheduling process.
I have:
=> feat: scheduler (2/): add ClusterScore related structs, etc.

pkg/scheduler/framework/status.go, pkg/scheduler/framework/status_test.go
It features some structs for plugins to report their running status.
I have:
=> feat: scheduler (4/): add status related structs

pkg/scheduler/queue/queue.go, pkg/scheduler/queue/queue_test.go
It features the a simple scheduling queue for the scheduler and related components to use.
I have:
=> feat: scheduler (1/): add schedule queue implementation

pkg/scheduler/framework/parallelizer/errorflag.go, pkg/scheduler/framework/parallelizer/errorflag_test.go, pkg/scheduler/framework/parallelizer/parallelizer.go, pkg/scheduler/framework/parallelizer/parallelizer_test.go
It features a parallelizer, which the scheduler frameworks uses to run tasks in parallel.
I have:
=> feat: scheduler (5/): add parallelizer

pkg/scheduler/framework/interface.go, pkg/scheduler/framework/profile.go, pkg/scheduler/framework/profile_test.go
It features the implementation for scheduler profile + the plugin interfaces to the scheduler.
I have:
=> feat: scheduler (6/): add scheduler profile + plugin interfaces

apis/placement/v1beta1/policysnapshot_types.go, pkg/controllers/clusterresourceplacement/placement_controller.go, pkg/controllers/clusterresourceplacement/placement_controller_test.go
CRPcontroller should not create a new scheduling policySnapshot for the scaling out/down cases.
- Remove the numberOfClusters when calculating the hash
- Remove the numberOfClusters from the scheduling policySnapshot spec
- Add the numberOfClusters annotation on scheduling policySnapshot
I have:
added scaling out/down UT
=> fix: remove the numberOfClusters from policySnapshot spec

apis/placement/v1beta1/zz_generated.deepcopy.go, pkg/scheduler/framework/framework.go, pkg/scheduler/framework/interface.go, pkg/scheduler/framework/profile.go, pkg/scheduler/framework/profile_test.go
It features the scaffolding for scheduler framework.
I have:
N/A.
To accommodate the uncertainties forward, and considering the fact that there is no easy way to fake a controller runtime manager, this PR does not include unit test (sanity check) for NewFramework(). Tests will be checked in with future PRs.
=> feat: scheduler (7/): add initial parts of scheduler framework

pkg/controllers/clusterresourceplacement/clusterresourceplacement_controller.go, pkg/controllers/clusterresourceplacement/placement_controller.go, pkg/controllers/clusterresourceplacement/resource_selector.go, pkg/controllers/clusterresourceplacement/resource_selector_test.go, pkg/utils/common.go, pkg/utils/controller/controller.go, pkg/utils/controller/controller_test.go
Differentiate the error types
- user error
- api server error (from cache or api server)
- unexpected behavior error
- expected behavior error
I have:
Need to add more UT in the future
=> feat: update the existing selectResources related func to support new API

apis/placement/v1beta1/resourcesnapshot_types.go, pkg/controllers/clusterresourceplacement/clusterresourceplacement_controller.go, pkg/controllers/clusterresourceplacement/clusterresourceplacement_controller_test.go, pkg/controllers/clusterresourceplacement/resource_selector_test.go
get or create cluster resource snapshots if needed.
I have:
Unit tests
=> feat: create clusterResourceSnapshots

pkg/controllers/clustershedulingpolicysnapshot/clusterschedulingpolicysnapshot_controller.go
When clusterSchedulingPolicySnapshot changes, will add a key into the CRP queue.
I have:
Will add the integration test in the next PR
=> feat: create a policy snapshot watcher for CRP controller

pkg/controllers/clusterresourceplacementwatcher/clusterresourceplacement_watcher.go, pkg/controllers/clusterresourceplacementwatcher/watcher.go
The current resourceWatcher will detect the CRP changes and queue the key into the CRPController queue.
Create a separate CRP watcher to monitor the CRP changes so that resourceWatcher will be only responsible for the dynamicResource changes.
Other controllers can access the cache using k8 runtime client instead of informer manager, which is more friendly than informer manager lister func (need to do the structure converstion).
I have:
Will add integration test in the next PR
=> feat: create a crp watcher

pkg/scheduler/framework/uniquename/uniquename.go, pkg/scheduler/framework/uniquename/uniquename_test.go
It features a utility that generates unique names for resource bindings.
I have:
Per earlier agreement, unit tests in this PR have a limited scope.
=> feat: scheduler (9/): add uniquename utility for preparing binding names

pkg/scheduler/framework/cyclestate.go, pkg/scheduler/framework/dummyplugin_test.go, pkg/scheduler/framework/framework.go, pkg/scheduler/framework/framework_test.go, pkg/scheduler/framework/status.go, pkg/scheduler/framework/status_test.go
It features more scheduling logic for PickAll type CRPs.
I have:
=> feat: scheduler (10/): add more scheduler logic

.github/workflows/build-publish-mcr.yml, .github/workflows/publish-image.yml, .github/workflows/trivy.yml
The `set-output` command is deprecated and will be disabled soon. 
For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Fixes #
I have:
Github action workflow
=> chore: deprecate set-output commands in github actions

apis/placement/v1beta1/commons.go, apis/placement/v1beta1/policysnapshot_types.go, pkg/controllers/membercluster/membercluster_controller.go, pkg/controllers/membercluster/membercluster_controller_integration_test.go, pkg/controllers/membercluster/membercluster_controller_test.go
=> feat: Add fleet resource label to fleet namespace

pkg/controllers/clusterresourceplacementwatcher/suite_test.go, pkg/controllers/clusterresourceplacementwatcher/watcher_integration_test.go, pkg/controllers/clustershedulingpolicysnapshot/controller_integration_test.go
- add integration tests for crp watcher
- Minor fix of the schedulingpolicysnapshot controller integration tests
Fixes #
I have:
integration tests
=> test: add integration tests for crp watcher

apis/placement/v1beta1/clusterresourceplacement_types.go, config/crd/bases/placement.azure.com_clusterresourceplacements.yaml, config/crd/bases/placement.azure.com_clusterschedulingpolicysnapshots.yaml
-  Remove the duplicate clusterName from FailedResourcePlacement as it's already in its parent, ResourcePlacementStatus.
- Add validation markers
Fixes #
I have:
=> interface: update crp status api and add validation markers

pkg/scheduler/framework/framework.go, pkg/scheduler/framework/framework_test.go, pkg/scheduler/framework/frameworkutils.go
This PR updates the scheduler logic to use patches (instead of updates) to avoid races.
It also adds a number of unit tests that wasn't included in previous scheduler PRs.
I have:
=> feat: use patches in scheduler to avoid races + add some more unit tests

apis/placement/v1beta1/policysnapshot_types.go, config/crd/bases/placement.azure.com_clusterschedulingpolicysnapshots.yaml, pkg/scheduler/framework/framework.go, pkg/scheduler/framework/framework_test.go, pkg/scheduler/framework/frameworkutils.go
It features more scheduling logic for PickAll type CRPs.
I have:
=> feat: scheduler (12/): add more scheduler logic 

pkg/controllers/clusterresourceplacementwatcher/watcher_integration_test.go
make sure the event has arrived before resetting the queue to fix the test flakiness
Fixes #
I have:
run the unit test ci
=> test: fix the crp watcher integration test flakiness

apis/placement/v1beta1/resourcesnapshot_types.go, config/crd/bases/placement.azure.com_clusterresourcesnapshots.yaml, pkg/controllers/clusterresourceplacement/controller.go, pkg/controllers/clusterresourceplacement/controller_test.go
- Add this annotation to help CRP to sort the snapshots in the group and work generator to create the work name.
- Fix the log to use the final policy snapshot name.
Now the first snapshot name will always be {CRPName}-{resourceIndex}-snapshot.
It helps to solve the duplication of resourceSnapshotName and now the name format is fixed and there is no ambiguity. 
This approach is simpler compared with other options' complexity otherwise the CRP name cannot contain "-" and not supporting it will hurt customer's experience.
Fixes #
I have:
=> feat: add the subindex annotation

pkg/scheduler/framework/framework.go, pkg/scheduler/framework/framework_test.go, pkg/scheduler/framework/frameworkutils.go, pkg/utils/common.go, pkg/utils/common_test.go
It features more scheduling logic for PickN type CRPs.
I have:
=> feat: scheduler (13/): add more scheduler logic

apis/placement/v1beta1/commons.go, apis/placement/v1beta1/policysnapshot_types.go, config/crd/bases/placement.azure.com_clusterschedulingpolicysnapshots.yaml
This PR adds generation related fields to the policy snapshot status API. This helps resolve some inconsistencies regarding status updates.
I have:
N/A
N/A
=> feat: add generation related fields to policy snapshot status

apis/placement/v1beta1/clusterresourceplacement_types.go, pkg/scheduler/queue/queue.go, pkg/scheduler/queue/queue_test.go, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go
It features more logic for the scheduler.
I have:
=> feat: scheduler (14/): add more scheduler logic

pkg/scheduler/framework/cyclestate.go, pkg/scheduler/framework/framework.go, pkg/scheduler/framework/framework_test.go, pkg/scheduler/framework/frameworkutils.go
It features more logic for scheduling PickN type CRPs.
I have:
**Important**: status related changes are to be sent in separate PR.
=> feat: scheduler (15/): add more scheduler logic

pkg/scheduler/framework/plugins/clusteraffinity/filtering.go, pkg/scheduler/framework/plugins/clusteraffinity/filtering_test.go, pkg/scheduler/framework/plugins/clusteraffinity/plugin.go, pkg/scheduler/framework/plugins/clusteraffinity/scoring.go, pkg/scheduler/framework/plugins/clusteraffinity/scoring_test.go
Implement the prefilter/filter/prescore/score extension points.
Fixes #
I have:
UT
=> feat: add clusteraffinity plugin implementations

pkg/scheduler/framework/plugins/topologyspreadconstraints/utils.go, pkg/scheduler/framework/plugins/topologyspreadconstraints/utils_test.go
This PR is part of the PRs that implement the in-tree scheduler framework plugins.
It features some scheduling logic for the topology spread constraints plugin.
I have:
=> feat: scheduler plugins (4/): add topology spread constraints plugin logic

pkg/scheduler/framework/framework.go, pkg/scheduler/framework/framework_test.go
It features more logic for scheduling PickN type CRPs.
I have:
=> feat: scheduler (16/): add more scheduler logic 

pkg/scheduler/framework/framework.go, pkg/scheduler/framework/framework_test.go, pkg/scheduler/framework/frameworkutils.go
It features more logic for scheduling PickN type CRPs.
Fixes #
I have:
-[x] Unit tests
=> feat: scheduler (17/): add more scheduler logic

pkg/scheduler/framework/cyclestate.go, pkg/scheduler/framework/cyclestate_test.go, pkg/scheduler/framework/cyclestateutils.go, pkg/scheduler/framework/framework.go, pkg/scheduler/framework/framework_test.go, pkg/scheduler/framework/plugins/clusteraffinity/filtering_test.go, pkg/scheduler/framework/plugins/clusteraffinity/scoring_test.go, pkg/scheduler/framework/plugins/topologyspreadconstraints/plugin_test.go, pkg/scheduler/framework/plugins/topologyspreadconstraints/utils.go, pkg/scheduler/framework/plugins/topologyspreadconstraints/utils_test.go, pkg/scheduler/framework/score.go, pkg/scheduler/framework/score_test.go
This PR updates the scheduler cycle state to allow easy queries of obsolete bindings.
I have:
This PR includes some naming change to better convey the usage; please let me know if the new names are less than ideal.
=> feat: update cycle state to allow queries for obsolete bindings

apis/types.go, cmd/hubagent/main.go, cmd/memberagent/main.go, examples/fleet_v1beta1_membercluster.yaml, pkg/controllers/internalmembercluster/v1alpha1/member_controller.go, pkg/controllers/internalmembercluster/v1alpha1/member_controller_integration_test.go, pkg/controllers/internalmembercluster/v1alpha1/member_controller_test.go, pkg/controllers/internalmembercluster/v1alpha1/member_suite_test.go, pkg/controllers/internalmembercluster/v1beta1/member_controller.go, pkg/controllers/internalmembercluster/v1beta1/member_controller_integration_test.go, pkg/controllers/internalmembercluster/v1beta1/member_controller_test.go, pkg/controllers/internalmembercluster/v1beta1/member_suite_test.go
Fixes #
I have:
v1beta1 IMC with status 
- The assumption from the RP side is that the member agent is installed for a managed cluster that joins the fleet, so when the member agent is installed RP get the associated member cluster CR name and passes it as a ENV variable 
-> Which is use to construct the member cluster namespaces name that gets passed 
-> To the hubOptions which get used to create the hub config for the hub client used by the member agent 
-> Meaning the member agent runs under the assumption that it's targeting one Member cluster CR's namespace. 
- Link: https://github.com/Azure/fleet/blob/main/cmd/memberagent/main.go#L80. But in our case we have two versions of controllers for v1alpha1 & v1beta1 but the caveat is that they can only target member cluster CRs (v1alpha1, …
=> feat: v1beta1 IMC controller

pkg/controllers/clusterresourceplacement/resource_selector.go, pkg/controllers/clusterresourceplacement/resource_selector_test.go
K8s api auto generated some [selector](https://github.com/kubernetes/kubernetes/blob/d4fde1e92a83cb533ae63b3abe9d49f08efb7a2f/pkg/registry/batch/job/strategy.go#L219)  for job based on the jobs' uid before it persist that will not work on the member cluster since its uid will change.
Fixes #456
I have:
UT
=> fix: remove the auto generated selectors for job

apis/placement/v1beta1/membercluster_types.go, pkg/scheduler/clustereligibilitychecker/checker.go, pkg/scheduler/clustereligibilitychecker/checker_test.go, pkg/scheduler/framework/framework.go, pkg/scheduler/framework/framework_test.go, pkg/scheduler/framework/frameworkutils.go, pkg/utils/common.go, pkg/utils/common_test.go
It features logic for scheduling CRPs with a fixed set of target clusters; it also updates the logic of status handling in the scheduler framework.
I have:
- This PR overlaps with some of the other PRs, specifically the cluster eligibility checking logic
- Some the unit tests are kept out to control the PR size; they will be sent in a separate PR.
=> feat: scheduler (18/): add more scheduler logic

apis/placement/v1beta1/clusterresourceplacement_types.go, apis/placement/v1beta1/zz_generated.deepcopy.go, config/crd/bases/placement.azure.com_clusterresourceplacements.yaml, config/crd/bases/placement.azure.com_clusterschedulingpolicysnapshots.yaml
[ClusterNames ](https://github.com/Azure/fleet/blob/main/apis/placement/v1beta1/clusterresourceplacement_types.go#L137) is a special case in the current API.
Feel it will be better to create it as a separate type to make the API clean.
Fixes #
I have:
=> interface: add a new placement type for a fixed set of clusters

pkg/controllers/clusterresourceplacement/controller.go
- finish the reconcile func of crp controller
Fixes #
I have:
=> feat: complete crp reconcile func

pkg/controllers/clusterresourceplacement/controller.go, pkg/controllers/clusterresourceplacement/controller_test.go
add crpGeneration so that scheduler could use this annotation to report the policySnapshot status.
Fixes #
I have:
unit tests
=> feat: add/update crpGenearation annotation on policy snapshot

Makefile, cmd/hubagent/main.go, cmd/hubagent/options/options.go, cmd/hubagent/options/validation.go, cmd/hubagent/options/validation_test.go, cmd/hubagent/workload/setup.go, cmd/memberagent/main.go, pkg/controllers/resourcechange/resourcechange_controller.go, pkg/controllers/resourcechange/resourcechange_controller_test.go, pkg/resourcewatcher/change_dector.go, pkg/resourcewatcher/event_handlers.go, pkg/scheduler/watchers/clusterresourceplacement/controller.go, pkg/scheduler/watchers/clusterresourceplacement/suite_test.go, pkg/scheduler/watchers/clusterschedulingpolicysnapshot/controller.go, pkg/scheduler/watchers/clusterschedulingpolicysnapshot/suite_test.go, test/integration/suite_test.go
- create v1beta1 controllers
Fixes #
I have:
May need to add flag for the webhook too. It depends on the test result and could be added in a separate PR.
=> feat: add v1beta1 flag to support v1beta1 controllers

examples/fleet_v1alpha1_membercluster.yaml, pkg/webhook/clusterresourceplacement/clusterresourceplacement_validating_webhook.go, pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook.go, pkg/webhook/validation/uservalidation.go, pkg/webhook/validation/uservalidation_test.go, pkg/webhook/webhook.go, test/e2e/e2e_test.go, test/e2e/framework/cluster.go, test/e2e/utils/helper.go, test/e2e/webhook_test.go
=> feat: Webhook for IMC

pkg/controllers/membercluster/v1beta1/membercluster_controller.go
This PR fixes an issue in member cluster controller where the wrong API group in owner reference may lead to events (e.g., InternalMemberCluster status updates) not being reconciled.
I have:
N/A
=> fix: use the cluster API group for owner reference in member cluster controller

charts/hub-agent/templates/deployment.yaml, charts/hub-agent/values.yaml
This PR adds toggles for API versions in the hub agent helm chart to allow usage of v1beta1 APIs on the upstream end.
I have:
N/A
=> feat: add API version toggles in hub agent helm charts

pkg/scheduler/watchers/membercluster/controller.go
This PR fixes a minor issue where logs with keys + values are recorded with `Info` rather than `InfoS`, which may lead to malformed texts.
I have:
N/A
=> fix: use InfoS for logs with keys/values

pkg/controllers/clusterresourceplacement/controller.go
This PR fixes an issue where the CRP controller will not emit any log when resources cannot be selected.
I have:
N/A
=> fix: report in logs when the CRP controller fails to select resources

cmd/hubagent/main.go, cmd/hubagent/workload/setup.go, test/integration/suite_test.go
This PR features a simple fix that runs the scheduler in a separate goroutine; otherwise the main function will be blocked.
I have:
N/A
=> fix: run scheduler in a separate goroutine

apis/cluster/v1beta1/membercluster_types.go, apis/interface.go, apis/placement/v1beta1/commons.go, apis/v1alpha1/commons.go, apis/v1alpha1/types.go, config/crd/bases/cluster.kubernetes-fleet.io_memberclusters.yaml, pkg/controllers/internalmembercluster/v1beta1/member_controller.go, pkg/controllers/membercluster/v1alpha1/membercluster_controller.go, pkg/controllers/membercluster/v1beta1/membercluster_controller.go, pkg/controllers/membercluster/v1beta1/membercluster_controller_integration_test.go, pkg/controllers/membercluster/v1beta1/membercluster_controller_test.go, pkg/controllers/membercluster/v1beta1/membercluster_suite_test.go, pkg/scheduler/clustereligibilitychecker/checker.go, pkg/scheduler/clustereligibilitychecker/checker_test.go, pkg/scheduler/framework/framework_test.go, pkg/scheduler/framework/frameworkutils.go, pkg/scheduler/framework/plugins/clustereligibility/plugin_test.go, pkg/scheduler/watchers/clusterresourceplacement/controller_integration_test.go, pkg/scheduler/watchers/membercluster/controller.go, pkg/scheduler/watchers/membercluster/controller_integration_test.go, pkg/scheduler/watchers/membercluster/suite_test.go, pkg/scheduler/watchers/membercluster/utils_test.go, pkg/utils/common.go
Fixes #
I have:
All the existing UT/IT/E2E should work
I am not sure the mc watcher for scheduler need to enqueue all the CRPs when a cluster left the fleet.
=> feat: remove the state in the member cluster CRD

apis/placement/v1beta1/binding_types.go, apis/placement/v1beta1/commons.go, apis/placement/v1beta1/work_types.go, pkg/controllers/clusterresourceplacement/placement_status.go, pkg/controllers/workgenerator/controller.go, pkg/controllers/workgenerator/controller_integration_test.go, pkg/controllers/workgenerator/controller_test.go
- declare the work related const in the api folder, so that
- v1beta1 controllers won't need to import work controller package any more.
- the annotations can use shared fleet prefix.
Fixes #
I have:
=> feat: declare v1beta1 work related const in the api folder

cmd/hubagent/options/options.go
Fixes #
I have:
We can directly alter the CCP chart to set the flag to true to test in RP, so disabling the fleet guard rail by default
=> fix: disable fleet guard rail by default

apis/cluster/v1beta1/zz_generated.deepcopy.go, apis/placement/v1beta1/zz_generated.deepcopy.go, apis/v1alpha1/zz_generated.deepcopy.go, pkg/controllers/workgenerator/controller.go, pkg/controllers/workgenerator/controller_integration_test.go, test/scheduler/pickall_integration_test.go
This PR fixes an issue where associated works are not deleted when the scheduler removes bindings.
I have:
N/A
=> fix: delete associated works when bindings are deleted

pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook.go, pkg/webhook/validation/uservalidation.go, pkg/webhook/validation/uservalidation_test.go, pkg/webhook/webhook.go, pkg/webhook/webhook_test.go, test/e2e/e2e_test.go, test/e2e/utils/helper.go, test/e2e/webhook_test.go
Fixes #
I have:
This PR provides a generic way to for the fleet guard rail to handle all name spaced resources in a group. This is part 1 a follow up PR for the remaining api groups
- autoscaling/v2 - horizontalpodautoscalers 
- cluster.kubernetes-fleet.io/v1beta1 - imc
- coordination.k8s.io/v1 - leases
- discovery.k8s.io/v1 - endpointslices
- events.k8s.io/v1 - events (already being selected)
- networking.k8s.io/v1 - Ingress class
- policy/v1 - PodDisruptionBudgets
- storage.k8s.io/v1 - csistoragecapacities
Groups covered in E2E for resources:
- **apps/v1**
- Deployment, DaemonSet, ReplicaSet
- **core/v1**
- Pod, Service, ConfigMap, Secret
- **batch/v1**
- CronJob, Job
- **rbac/v1**
- Role, RoleBinding
=> feat: Webhook for reserved namespace resources part-1

pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook.go, pkg/webhook/validation/uservalidation.go, pkg/webhook/validation/uservalidation_test.go
Fixes #
I have:
While testing in RP discovered IMC update being rejected by fleet guard rail, 
https://dataexplorer.azure.com/clusters/akse2e.westus2/databases/AKSE2ECustomer?query=H4sIAAAAAAAAA32Q0UvDMBDG3/dXHEVoB23JOqdO2YOCe/JBcE++SNp+6zLSpiQ358A/3mRoFSdCCLnc/b777jSYXhxLyyvVghZUSwb7ZxIXophmYp6J2WoyuxbCn1wI8RyPb0Y6YOjq/6Bi+gtaaoBvG3R8/+ovN3qn/QYW9GhRKYcg9sSy7akE74GOkh/W8nzoOB5IFLjbKV3TYkERSl1fzidXorg4j3wJ3tgD9GAab9EHVla8daZL4rNcmyZOqbemh2UFRynxoYdZJ46t6ppx6OHTW1R84i+lyg/cGHtIg3o62Bh8hZ4b6ShSjjrDJLU2e9QRGfudW0ql/d8AfYkeh1mHZWWbXZnJsLEj+UdBi7aE/azxSsbWsFQeTncqXfUBEQbZEe0BAAA=
let _startTime = datetime('2023-09-05T15:00:00.000Z');
let _endTime = datetime('2023-09-05T23:00:00.000Z');
FleetAgentEvents
| where PreciseTimeStamp between (_startTime .. _endTime)
| where e2eBuild == "ebld79180264" …
=> fix: Use subresource to check for IMC status update

pkg/controllers/membercluster/v1beta1/membercluster_controller.go
This PR fixes an issue in member cluster where it uses the old Work API.
I have:
=> fix: use new forked Work API in member cluster controller

pkg/controllers/membercluster/v1beta1/membercluster_controller.go
This PR fixes an issue where empty key/value pair is logged in member cluster controller.
I have:
Not a critical fix.
=> fix: address an issue where empty reference is logged in member cluster controller

pkg/controllers/clusterresourceplacement/controller.go
The scheduled & sync events could be skipped if the rollout happens too quickly.
Record the schedule & sync events before rollout completes.
Fixes #
I have:
Manual test
=> fix: change the order of events in order to record all the events

pkg/controllers/membercluster/v1beta1/membercluster_controller.go, pkg/controllers/membercluster/v1beta1/membercluster_controller_test.go, pkg/utils/common.go
This PR fixes an issue where the v1beta1 hub agent still applies permissions tailored for v1alpha1 APIs, which leads to member agents failing to join.
I have:
=> fix: set up correct access control in v1beta1 hub agents

pkg/scheduler/watchers/clusterschedulingpolicysnapshot/controller.go, pkg/scheduler/watchers/clusterschedulingpolicysnapshot/controller_integration_test.go
This PR fixes an issue where the scheduler watcher ignores observed CRP annotation changes.
I have:
=> fix: watch for observed CRP annotation change in scheduler watcher

apis/placement/v1beta1/commons.go, cmd/hubagent/workload/setup.go, pkg/controllers/clusterresourceplacement/placement_controllerv1alpha1.go, pkg/controllers/memberclusterplacement/membercluster_controller.go, pkg/controllers/resourcechange/resourcechange_controller.go, pkg/controllers/resourcechange/resourcechange_controller_test.go, pkg/resourcewatcher/change_dector.go, pkg/utils/apiresources.go, pkg/utils/common.go, test/e2e/actuals_test.go, test/e2e/placement_test.go, test/e2e/setup_test.go, test/e2e/utils_test.go
This PR fixes an issue where the resource change processing controller only processes v1alpha1 CRPs, which leads to unreasonably long delays for fleets with v1beta1 API to apply resource changes.
I have:
Expedient fixes, which should get refactored in the future when v1alpha1 API becomes obsolete.
This also edits the E2E tests we have right now a little bit to verify the effectiveness.
=> fix: set the resource change processing controller to handle v1beta1 CRPs correctly + ignore member cluster updates

apis/placement/v1beta1/zz_generated.deepcopy.go, pkg/scheduler/framework/framework.go, pkg/scheduler/framework/framework_test.go, pkg/scheduler/framework/frameworkutils.go
This PR fixes an issue where clusters that are scored but not eventually picked do not have their scores reported in the status.
I have:
Not an urgent fix; affects status only,
=> fix: report the scores of clusters that are not picked

pkg/controllers/clusterresourceplacement/controller.go, pkg/controllers/clusterresourceplacement/controller_test.go
This PR fixes an issue where the CRP controller would overwrite CRP object annotations when reconciling CRPs of the PickN placement; when this issues occurs, the CRP object would lose its CRP generation annotation, which would fail all future reconciliation loops.
I have:
=> fix: stop CRP controller from overwriting CRP annotations when reconciling CRPs of the PickN placement type

pkg/utils/validator/clusterresourceplacement.go, pkg/utils/validator/clusterresourceplacement_test.go, test/e2e/webhook_test.go
=> feat: v1beta1 CRP validation for PickAll Placement policy

test/e2e/actuals_test.go, test/e2e/placement_selecting_resources_test.go
Test
- When resource selectors are updated 
- When configured with a revision history limit
Fixes #
I have:
=> test: add e2e test to validate the revision history

pkg/controllers/membercluster/v1beta1/membercluster_controller.go
Currently, we have an event shows as "clusterunknonw" which can be confusing.
Fixes #
I have:
=> fix: make the join event message clear.

pkg/scheduler/framework/framework.go, pkg/scheduler/framework/framework_test.go
This PR fixes an issue where policy snapshot status will not be updated when the scheduling policy itself does not change, yet the CRP generation is incremented (i.e., resource only change).
It also added a unit test that is not checked in in prev. PRs.
I have:
=> fix: update policy snapshot status in cases where only the observed CRP generation changes

examples/fleet_v1beta1_membercluster.yaml, pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook.go, pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook_test.go, pkg/webhook/webhook.go, pkg/webhook/webhook_test.go, test/e2e/fleet_guard_rail_test.go, test/e2e/resources_test.go, test/e2e/setup_test.go, test/e2e/utils_test.go
=> feat: guard rail for v1beta1 MC

pkg/controllers/rollout/controller.go, pkg/controllers/rollout/controller_integration_test.go, pkg/controllers/rollout/controller_test.go, test/e2e/enveloped_object_placement_test.go
Rollout can get stuck when there are failed to apply bindings since there are already max unavailable bindings. The fix is to update the failed bindings first since it won't make more bindings unavailable since they are already unavailable anyway.
Fixes #
I have:
- [x ] Run `make reviewable` to ensure this PR is ready for review.
UT/IT/E2E
=> fix: fix the case that rollout stuck when there are failed to apply binding

pkg/controllers/clusterresourceplacement/controller.go, pkg/controllers/clusterresourceplacement/controller_integration_test.go, pkg/controllers/clusterresourceplacement/placement_status.go, pkg/controllers/clusterresourceplacement/placement_status_test.go, pkg/utils/condition/condition.go, pkg/utils/condition/condition_test.go
- build CRP ResourcePlacementStatus using existing conditions
- build CRP sync condition by using clusterResouceBinding bound condition instead of works
- change the CRP reconcile time when we are waiting for resource applied to depend on the apply unavailable time.
Fixes #
I have:
Unit tests
=> fix: fix the CRP condition

test/e2e/fleet_guard_rail_test.go, test/e2e/utils_test.go
=> fix: flaky fleet guard rail E2E where namespace is terminating

apis/placement/v1beta1/policysnapshot_types.go, apis/placement/v1beta1/resourcesnapshot_types.go
This PR fixes an issue where we use both camel case and hyphen case for our labels and annotations.
I have:
N/A
N/A
=> fix: use hyphen case for all labels and annotation names

docs/api-references.md
This PR adds API reference documentation.
N/A
N/A
=> docs: Add API reference

pkg/utils/common.go, pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook_test.go, pkg/webhook/validation/uservalidation.go, pkg/webhook/validation/uservalidation_test.go, test/e2e/fleet_guard_rail_test.go, test/e2e/v1alpha1/webhook_reserved_namespace_resources_test.go, test/e2e/v1alpha1/webhook_test.go
=> feat: Pretty print fleet guard rail messages

README.md, docs/concepts/Scheduler/README.md, docs/howtos/README.md, docs/howtos/affinities.md, docs/howtos/crp.md, docs/howtos/topology-spread-constraints.md
fix doc typos and minor changes
Fixes #
I have:
=> fix: fix doc typos and minor changes

docs/howtos/crp.md
adjust rollout document.
Fixes #
I have:
=> fix: adjust rollout document.

pkg/webhook/webhook.go, pkg/webhook/webhook_test.go
Fixes #
I have:
UTs and exisiting E2Es
=> feat: separate validating webhook config for fleet guard rail

Makefile, apis/placement/v1beta1/zz_generated.deepcopy.go, cmd/hubagent/options/options.go, cmd/hubagent/options/validation.go, cmd/hubagent/workload/setup.go, pkg/controllers/clusterresourceplacement/placement_controllerv1alpha1.go, pkg/controllers/clusterresourceplacement/resource_selector.go, pkg/controllers/clusterresourceplacement/suite_test.go, pkg/resourcewatcher/change_dector.go, pkg/utils/apiresources.go, pkg/utils/apiresources_test.go
- Add `--allowed-propagating-apis` option to hub-agent command.
- Validate that `--allowed-propagating-apis` and `--skipped-propagating-apis` are mutually exclusive and cannot be specified together.
- Refactor `DisabledResourceConfig` type into a generic `ResourceConfig` so that we can reuse it for both `Allowed` and `Disabled` resource configs. During initializing `DisabledResourceConfig`, fleet and built-in resources are configured.
- Update `change_detector` to watch only the allowed resources if specified.
- Update `resource_selector` to only select allowed resources if specified.
- Add a util function with unit test to determine if a ResourceConfig is empty
- Add make `help` recipe for developers to list the available commands in the Makefile.
Fixes #633 
I have:
Verify that the …
=> feat: add allowedPropagatingAPIs option for resource selection

pkg/controllers/clusterresourceplacement/controller.go, pkg/controllers/clusterresourceplacement/controller_test.go, pkg/controllers/rollout/controller.go
Fixes #
I have:
This PR contains core logic and UTs
=> feat: create multiple resource snapshots for same group index

pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook.go, pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook_test.go, pkg/webhook/validation/uservalidation.go, pkg/webhook/webhook.go, test/e2e/fleet_guard_rail_test.go, test/e2e/resources_test.go, test/e2e/setup.sh, test/e2e/utils_test.go, test/e2e/v1alpha1/webhook_test.go
Fixes #
I have:
- Allow member agent to create/update/delete internal fleet namespaced resources.
- Deny users from creating internal fleet namespaced resources in fleet/kube prefixed namesapces
=> fix: fleet guard rail allows member agent to CREATE/UPDATE/DELETE

Makefile, charts/hub-agent/templates/deployment.yaml, charts/hub-agent/values.yaml, cmd/hubagent/main.go, cmd/hubagent/options/options.go, cmd/hubagent/options/validation.go, cmd/hubagent/options/validation_test.go, pkg/webhook/webhook.go
The fleet web hook service name is hard code right now. The service name also usually in the user's deployment. That make the user can't use difference service name in deployment.
This PR to parameterize the web hook service name.
Fixes #
I have:
=> feat: parameterize the web hook service name

docs/api-references.md, docs/faq.md
A new flag `--allowed-propagating-apis` was introduced in #633. I am updating the reference docs to describe how the user can use this flag.
Fixes #649
I have:
Rendered the markdown locally and ran `make test`
- api-resources doc has been updated to suggest that if a namespace is selected, the default behavior of ALL resource propagation can be controlled with this flag.
=> docs: update docs for allowed propagating apis flag

pkg/controllers/internalmembercluster/v1beta1/member_controller_integration_test.go
Fixes #
I have: made the RequeAfter comparison inclusive to include all +/- jitter percent in internal member cluster controller integration test.
=> fix: fix flaky internalmembercluster contoller integration test

apis/cluster/v1beta1/membercluster_types.go, apis/placement/v1beta1/clusterresourceplacement_types.go, config/crd/bases/cluster.kubernetes-fleet.io_memberclusters.yaml, config/crd/bases/placement.kubernetes-fleet.io_clusterresourceplacements.yaml, config/crd/bases/placement.kubernetes-fleet.io_clusterschedulingpolicysnapshots.yaml
Fixes #
I have:
Decided to go with custom objects for taints and tolerations because,
- The objects from "k8s.io/api/core/v1" were specifically created for nodes, pods and hence has comments explicitly specifying they were related to nodes and pods 
- Taint had TimeAdded field for NoExecute 
- Toleration has TolerationSeconds field for NoExecute
=> interface: Taints & Tolerations API

pkg/webhook/webhook.go
Fixes #
I have:
**fleet guard rail validating webhook configuration:**
**fleet validating webhook configuration:**
=> fix: change failure policy, timeout for validating webhooks

apis/placement/v1beta1/clusterresourceplacement_types.go
This PR fixes a minor issue where the example formulas for sorting properties are misplaced in the API comments.
I have:
N/A
N/A
=> fix: swap the example formulas for sorting properties in the API comments

test/scheduler/actuals_test.go, test/scheduler/pickall_integration_test.go, test/scheduler/pickn_integration_test.go, test/scheduler/tainttoleration_integration_test.go, test/scheduler/utils_test.go
Fixes #
I have:
Integration tests with the plugin enabled only for tests.
Main Workflows covered:
- Special case for PickFixed adding taints shouldn't matter since plugin won't be run
- Add taint to existing cluster, Create CRP without tolerations, cluster is not picked
- Add taint to existing cluster, Create CRP with tolerations, cluster is picked with matching toleration
- Add taint to existing cluster, Create CRP without tolerations, , cluster is not picked, CRP is updated with tolerations, cluster is picked with matching toleration after CRP udpate
- Create CRP without tolerations, Create new cluster with taints and mark it as healthy to trigger scheduling cycle, cluster is not picked
- Create CRP with tolerations, Create new cluster with taints and mark it as healthy to trigger …
=> test: ITs for taints & tolerations plugin

pkg/controllers/work/applied_work_syncer_test.go, pkg/controllers/work/apply_controller.go, pkg/controllers/work/apply_controller_helper_test.go, pkg/controllers/work/apply_controller_integration_test.go, pkg/controllers/work/apply_controller_test.go, pkg/controllers/workgenerator/controller.go, pkg/utils/common.go, pkg/utils/condition/condition.go, test/e2e/actuals_test.go, test/e2e/enveloped_object_placement_test.go, test/e2e/placement_selecting_resources_test.go, test/e2e/resources/test-deployment.yaml, test/e2e/resources/test-envelop-deployment.yaml, test/e2e/resources_test.go, test/e2e/rollout_test.go, test/e2e/setup_test.go, test/e2e/utils_test.go, test/utils/controller/controller.go
Support track resource availability on work agent and reflect it on the work status. 
I have:
=> feat: work agent track availability

pkg/controllers/membercluster/v1beta1/membercluster_controller.go, pkg/controllers/membercluster/v1beta1/membercluster_controller_integration_test.go, pkg/controllers/membercluster/v1beta1/membercluster_controller_test.go
This PR enables the MC controller to copy status fields for property-based scheduling from IMC to MC.
I have:
E2E tests will be added in a separate PR.
=> feat: property-based scheduling: add property provider support to MC controller

pkg/scheduler/watchers/membercluster/controller.go, pkg/scheduler/watchers/membercluster/controller_integration_test.go
This PR adds support for property-based scheduling in the scheduler member cluster watcher.
I have:
N/A
=> feat: property-based scheduling: add support for property-based scheduling in the scheduler member cluster watcher

Makefile
This PR fixes an issue where unit tests would fail due to the latest version of envtest refers to a Go version that is too new.
I have:
N/A
=> fix: (temporarily) use a fixed version of `envtest` due to Go version mismatches in the latest version

pkg/webhook/add_handler.go, pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook.go, pkg/webhook/webhook.go, pkg/webhook/webhook_test.go
Fixes #
I have: added webhook configuration for ClusterResourceOverride
=> feat: add cluster resource override validation webhook configuration

pkg/controllers/work/applied_work_syncer_integration_test.go, pkg/controllers/work/applier.go, pkg/controllers/work/applier_client_side.go, pkg/controllers/work/applier_fail_if_exists.go, pkg/controllers/work/applier_server_side.go, pkg/controllers/work/applier_server_side_test.go, pkg/controllers/work/applier_test.go, pkg/controllers/work/apply_controller.go, pkg/controllers/work/apply_controller_integration_test.go, pkg/controllers/work/apply_controller_test.go, pkg/controllers/work/suite_test.go, pkg/utils/defaulter/work.go, pkg/utils/defaulter/work_test.go, test/e2e/placement_selecting_resources_test.go
- Refactor code to support server side apply
- Add the conflict work check for both types. If the existing resource is owned by other work, the apply strategy should be the same.
Fixes #
I have:
Add new UT
existing tests should make sure no regression.
upstream does not have a fake client to support apply method very well.
Will add IT/e2e tests in a separate PR.
=> feat: support apply strategy

pkg/controllers/rollout/controller.go, pkg/controllers/rollout/controller_test.go
Fixes #
I have:
Full agent logs: [hub-agent-logs.txt](https://github.com/Azure/fleet/files/14878291/hub-agent-logs.txt)
Noticed that rollout had stalled when testing, logs that pointed to the issue
I0404 21:22:48.072775       1 rollout/controller.go:408] "Calculated the targetNumber" clusterResourcePlacement="crp-3" targetNumber=1 readyBindingNumber=0 canBeUnavailableBindingNumber=0 canBeReadyBindingNumber=0 boundingCandidateNumber=0 removeCandidateNumber=0 updateCandidateNumber=0 applyFailedUpdateCandidateNumber=1
I0404 21:22:48.072953       1 rollout/controller.go:147] "No bindings are out of date, stop rolling" clusterResourcePlacement="crp-3"
I0404 21:22:48.073359       1 rollout/controller.go:61] "Rollout reconciliation loop ends" clusterResourcePlacement="crp-3" latency=10
=> fix: include applyFailedUpdateCandidates length in need rollout check

apis/placement/v1/clusterresourceplacement_types.go, apis/placement/v1beta1/clusterresourceplacement_types.go, config/crd/bases/placement.kubernetes-fleet.io_clusterresourceplacements.yaml, hack/loadtest/util/placement.go
```
$kubectl get crp
NAME    GEN   SCHEDULED   SCHEDULED-GEN   AVAILABLE   AVAILABLE-GEN   AGE
crp-1   1     True        1               True        1               173m
$ kubectl get crp -o wide
NAME    GEN   TYPE      SCHEDULED   SCHEDULED-GEN   WORK-SYNCHRONIZED   WORK-SYNCHRONIZED-GEN   AVAILABLE   AVAILABLE-GEN   AGE
crp-1   1     PickAll   True        1               True                1                       True        1               173m
```
Fixes # 793
I have:
local test
use "-" to split the column name to make it consistent with k8 deployment output,
```
kubectl get deployment coredns -n kube-system -o wide
NAME      READY   UP-TO-DATE   AVAILABLE   AGE    CONTAINERS   IMAGES                                    SELECTOR
coredns   2/2     2            2           162m   coredns …
```
=> feat: support kubectl -o wide

apis/placement/v1/clusterresourceplacement_types.go, apis/placement/v1beta1/clusterresourceplacement_types.go, pkg/utils/validator/clusterresourceplacement.go, pkg/utils/validator/clusterresourceplacement_test.go
Bump the min maxUnavailable to 1 to avoid rolling out stuck.
Fixes #
I have:
=> fix: bump the min maxUnavailable to 1

pkg/controllers/clusterresourceplacement/placement_status.go, pkg/scheduler/queue/queue.go, pkg/scheduler/scheduler.go, pkg/scheduler/watchers/clusterschedulingpolicysnapshot/watcher.go, pkg/scheduler/watchers/membercluster/watcher.go
1. Fix a bug that the scheduler forget to forget an item when there is no error. 
2. Adjust some logs
Fixes #
I have:
=> fix: forget the item on scheduling success

hack/Azure/setup/README.md, hack/Azure/setup/labelMC.sh
Fixes #
I have: provided a script that will take the member clusters on a fleet and add the user provided label to the number of member clusters the user would like at random. As well as, update the readme for instructions.
=> docs: member cluster labeling script

pkg/controllers/work/apply_controller.go, pkg/controllers/work/apply_controller_test.go
The "Available" condition of a deployment is not sufficient to indicate that a deployment is updated correctly so we need
to tighten up the standard.
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#complete-deployment
Fixes #
I have:
=> fix: check the deployment  available replica count instead

pkg/controllers/work/applier.go, pkg/controllers/work/applier_test.go, test/e2e/placement_apply_strategy_test.go, test/e2e/placement_selecting_resources_test.go
Allow agent to take over the resource if it has no owner reference.
Fixes #
I have:
UT and e2e
=> fix: own the resource when the existing resource is not owned by other applier

pkg/propertyprovider/commons.go, pkg/scheduler/framework/plugins/clusteraffinity/types.go, pkg/utils/validator/clusterresourceplacement.go, pkg/utils/validator/clusterresourceplacement_test.go
Fixes #
I have:
This validation is to prevent users from providing random property names with prefix resources.kubernetes-fleet.io/
=> fix: validation for property selector name

hack/Azure/setup/README.md, hack/Azure/setup/joinMC.sh
Fixes #
I have: fixed minor doc typos
=> docs: fix doc typos

pkg/scheduler/framework/framework_test.go, pkg/scheduler/framework/frameworkutils.go
This PR fixes a minor issue where duplicate entries might occur in cluster decisions when a cluster is picked and then unpicked without having a scheduling policy change.
I have:
=> fix: address a minor issue that might cause duplicate entries in cluster decisions (status)

pkg/controllers/membercluster/v1beta1/membercluster_controller.go, pkg/controllers/membercluster/v1beta1/membercluster_controller_integration_test.go, pkg/controllers/membercluster/v1beta1/membercluster_controller_test.go, pkg/controllers/membercluster/v1beta1/membercluster_suite_test.go, test/e2e/enveloped_object_placement_test.go, test/e2e/join_and_leave_test.go
1.  fix the immediate bug by just listing all the work in the cluster namespace.
2. issue the work finalizer removal in parallel.
3. issue a foreground delete namespace before removing the finalizer on the MC object.
4. handle the edge case that the imc does not exist.
Fixes #
I have:
=> fix:  enhance the member cluster leave flow

apis/cluster/v1/membercluster_types.go, apis/cluster/v1beta1/membercluster_types.go, config/crd/bases/cluster.kubernetes-fleet.io_memberclusters.yaml
Fixes #
I have:
ran make manifests
=> feat: add print column to show member agent HB

docker/hub-agent.Dockerfile, docker/member-agent.Dockerfile, docker/refresh-token.Dockerfile
ERROR: failed to solve: golang:1.22.4: failed to resolve source metadata for docker.io/library/golang:1.22.4: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/golang/manifests/sha256:c8736b8dbf2b12c98bb0eeed91eef58ecef52b8c2bd49b8044531e8d8d8d58e8: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
Replace docker image
https://github.com/Azure/fleet/actions/runs/9871630314/job/27267136500
Fixes #
I have:
=> chore: use mcr base image instead of docker

pkg/utils/common.go, pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook.go, pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook_test.go, pkg/webhook/validation/uservalidation.go, test/e2e/fleet_guard_rail_test.go, test/e2e/scheduler_watchers_test.go, test/e2e/setup_test.go, test/e2e/utils_test.go, test/e2e/webhook_test.go
Fixes #
I have:
UTs and upstream E2E tests
Handle fleet/upstream MC resources differently,
For fleet MC:
- Deny normal users from modifying the fleet cluster resource ID annotation (update, delete)
- Allow special authenticated users to update all fleet pre-fixed annotations values and delete some fleet pre-fixed annotations (update)
- Deny special authenticated users to delete all fleet pre-fixed annotations (we have a hard requirement that at least one annotation should have pre-fix fleet.azure.com)
- Only special authenticated users can update ownerReferences, finalizers, spec, status (taints are ignored)
- All other changes to objectMeta are allowed for all users
For upstream MC:
Allow all users to CREATE/DELETE upstream MC resource without cluster resource id annotation
- Deny normal …
=> feat: handle fleet/upstream MC resources differently in fleet guard rail

docs/getting-started/kind.md, docs/getting-started/on-prem.md, hack/membership/join.sh, test/e2e/setup.sh
Fix the kind join script as kind cluster can't pull images directly from MCR
Fixes #
I have:
=> fix: fix the kind join script

.github/workflows/ci.yml, test/e2e/enveloped_object_placement_test.go, test/e2e/rollout_test.go, test/e2e/setup_test.go
The github action will be stopped because of no disk space.
`##[warning]You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 48 MB`
- Delete files to free space
- increase the eventually duration for the deployment to reduce the flakiness
reference link, https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
Fixes #
I have:
=> chore: fix the ci github action

go.mod, go.sum
CVE-2024-41110 was introduced by github.com/crossplane/crossplane-runtime v0.20.1
Recommendation,
Upgrade [github.com/docker/docker](http://github.com/docker/docker) from v24.0.4+incompatible to 25.0.6 to fix the vulnerability.
This package was removed from the latest crossplane-runtime.
Fixes #
I have:
=> fix: fix the critical CVE used by the tests

pkg/controllers/rollout/controller.go, pkg/controllers/rollout/controller_integration_test.go, pkg/controllers/rollout/controller_test.go, test/e2e/setup.sh
=> feat: calculate the time we need to wait for the first applied but not ready binding to be ready.

go.sum, pkg/controllers/clusterresourceplacement/controller.go, pkg/controllers/clusterresourceplacement/resource_selector.go, pkg/controllers/clusterresourceplacement/resource_selector_test.go
fix the order between namespace and crd resources in the resource snapshots so that the snapshot doesn't change when there is no resource changes
Fixes #
I have:
=> fix: fix the order between namespace and crd resources in the resource snapshots

apis/placement/v1beta1/clusterresourceplacement_types.go, config/crd/bases/placement.kubernetes-fleet.io_clusterresourcebindings.yaml, config/crd/bases/placement.kubernetes-fleet.io_clusterresourceplacements.yaml, config/crd/bases/placement.kubernetes-fleet.io_works.yaml, pkg/controllers/work/apply_controller.go
=> feat: add take over and drift detection options in CRP API

pkg/controllers/workgenerator/controller.go, pkg/controllers/workgenerator/controller_test.go
I have:
- Add unexpected error for when rolloutStarted condition is not found.
- Fixed corresponding UT: Compares RolloutStarted Condition is the same as tt.latestBinding after conflict.
=> fix: update updateBindingStatusWithRetry and corresponding UT

.github/workflows/ci.yml, .github/workflows/code-lint.yml, .github/workflows/trivy.yml, .golangci.yml, docker/hub-agent.Dockerfile, docker/member-agent.Dockerfile, docker/refresh-token.Dockerfile
Fix the CVE
hubagent (gobinary)
===================
Total: 1 (HIGH: 1, CRITICAL: 0)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬────────────────┬───────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version  │                           Title                           │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼────────────────┼───────────────────────────────────────────────────────────┤
│ stdlib  │ CVE-2024-34156 │ HIGH     │ fixed  │ 1.22.4            │ 1.22.7, 1.23.1 │ encoding/gob: golang: Calling Decoder.Decode on a message │
│         │                │          │        │                   │                │ which contains deeply nested structures... …
=> fix: bump go build version to 1.22.7

pkg/controllers/workgenerator/controller.go, pkg/controllers/workgenerator/controller_integration_test.go, pkg/controllers/workgenerator/controller_test.go, test/e2e/enveloped_object_placement_test.go
Fixes #
I have: add a check for rollout condition before the status is generated
=> fix: fix unexpected alert race condition 

pkg/scheduler/framework/plugins/tainttoleration/filtering.go
=> fix: add log for untolerated taint

go.mod, go.sum
This PR updates crossplane-runtime to the latest version as older version was causing a high governance alert (critical CVE: CVE-2024-41110) for the azure/fleet repo.
Fixes #
I have:
=> fix: update-crossplane-runtime-version to fix CVE

apis/cluster/v1beta1/zz_generated.deepcopy.go, apis/placement/v1beta1/clusterresourceplacement_types.go, apis/placement/v1beta1/zz_generated.deepcopy.go, apis/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/placement.kubernetes-fleet.io_clusterresourcebindings.yaml, config/crd/bases/placement.kubernetes-fleet.io_clusterresourceplacements.yaml, config/crd/bases/placement.kubernetes-fleet.io_clusterstagedupdateruns.yaml, config/crd/bases/placement.kubernetes-fleet.io_works.yaml
This PR addresses some inconsistent JSON tags in the code.
I have:
N/A
N/A
=> fix: inconsistent JSON tags

Makefile, README.md, pkg/webhook/validation/uservalidation.go, pkg/webhook/validation/uservalidation_test.go, test/e2e/setup.sh
Fixes #
I have:
Addressing https://github.com/Azure/fleet/pull/911#issuecomment-2428232162
- KIND started using kubeadm https://kind.sigs.k8s.io/docs/user/configuration/#kubeadm-config-patches
- https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/#generate-kubeconfig-files-for-control-plane-components; kubeadm creates kubernetes-admin user in kubeadm:cluster-admin group
Before this change kubernetes-admin use belonged to system:masters group
=> feat: add kubeadm cluster-admin group in fleet guard rail & bump kindest node to use 1.30.0

cmd/authtoken/main.go, docker/refresh-token.Dockerfile, pkg/authtoken/interfaces.go, pkg/authtoken/providers/azure/azure_msi.go, pkg/authtoken/providers/secret/k8s_secret.go, pkg/authtoken/token_refresher.go, pkg/authtoken/token_refresher_test.go, pkg/authtoken/token_writer.go, pkg/authtoken/token_writer_test.go
Move interfaces.go from interfaces to authtoken/providers directory and add missing documentation for type AuthToken struct, AuthTokenProvider interface and AuthTokenWriter interface.
Fixes #
I have:
=> refactor: Move file from interfaces to authtoken package directories and add comments

apis/placement/v1beta1/binding_types.go, cmd/hubagent/workload/setup.go, pkg/scheduler/framework/framework.go, pkg/scheduler/framework/framework_test.go, pkg/scheduler/framework/frameworkutils.go, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go, pkg/scheduler/watchers/clusterresourcebinding/controller_integration_test.go, pkg/scheduler/watchers/clusterresourcebinding/suite_test.go, pkg/scheduler/watchers/clusterresourcebinding/watcher.go, test/scheduler/actuals_test.go, test/scheduler/suite_test.go
Fixes #
I have:
- Adding scheduler clean up finalizers for CRBs when CRBs are created in a scheduling cycle
- Removing scheduler clean up finalizers for CRBs when CRBs are deleting with deleting timestamp
- Added CRB scheduler watcher to pick up deleting CRBs and enqueue CRP name to trigger scheduling cycle, also added watcher IT
- Added logic to clean up CRBs, by removing scheduler clean up finalizer when CRP is deleting
These changes are needed for the new PlacementEviction API
=> feat: add, remove finalizer for CRB in Scheduler and scheduler watcher for CRB

pkg/controllers/workgenerator/controller.go, pkg/controllers/workgenerator/controller_test.go
=> fix: initialize the annotation map before assigning a value

.github/workflows/trivy.yml
The trivy action was failing from time to time due to throttling when pulling trivy image from `ghcr.io` registry. Thus we switch to use `mcr` instead.
Fixes #
I have:
Tested here: https://github.com/Azure/fleet/actions/runs/11749964574/job/32737242689
`08T21:44:27Z	INFO	[vulndb] Artifact successfully downloaded	repo="mcr.microsoft.com/mirror/ghcr/aquasecurity/trivy-db:2"`
=> chore: fix trivy workflow by using mcr trivy images

pkg/utils/cloudconfig/azure/config.go, pkg/utils/cloudconfig/azure/config_test.go, pkg/utils/cloudconfig/azure/test/azure_valid_config.json, test/e2e/azure_valid_config.yaml
Fixes #
I have: remove `VnetName` check from common package. This is so that the `VnetName` is not required on fleet-networking repo.
Will add check to another PR where I load the cloudConfig.
=> fix: remove VnetName check from common cloudConfig package

apis/placement/v1alpha1/common.go, apis/placement/v1beta1/commons.go, pkg/controllers/updaterun/controller.go, pkg/controllers/updaterun/controller_integration_test.go, pkg/controllers/updaterun/controller_test.go, pkg/controllers/updaterun/suite_test.go, pkg/utils/common.go, pkg/utils/condition/condition.go
Add the ClusterStagedUpdateRun controller and handle the CR deletion
Fixes #
I have:
=> feat: add ClusterStagedUpdateRun controller and handle deletion

pkg/utils/apiresources.go, pkg/utils/apiresources_test.go
The fix is needed for supporting new networking feature
Fixes #
I have:
=> feat: disable placing atm related resources

pkg/controllers/clusterresourceplacement/placement_status.go, pkg/controllers/clusterresourceplacement/placement_status_test.go
This PR enables the CRP controller to copy drift/diff details as reported in the binding status to the CRP status.
I have:
Currently drift/diff details are not yet populated.
=> feat: drift detection/takeover prerequisite (1/): enable the CRP controller to copy drift/diff details to the status

pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook_test.go, pkg/webhook/validation/uservalidation.go, pkg/webhook/validation/uservalidation_test.go
=> fix: allow aks-support user in fleet guard rail

pkg/controllers/rollout/controller_test.go
Discrepancies found by Arvind when looking at unit tests.
I have:
- Corrected variable naming based on readiness 
- Updated test cases accordingly
=> fix: fix TestPickBindingsToRoll rollout unit test

Makefile
Fix too many requests error
```
Unable to find image 'multiarch/qemu-user-static:5.2.0-2' locally
docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
```
Fixes #
I have:
=> fix: use mcr image to avoid too many requests error

Makefile
Fix the image failure,
```
#1 pulling image moby/buildkit:buildx-stable-1 0.9s done
#1 ERROR: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
Fixes #
I have:
=> fix: fix the publish pipeline by using mcr image

pkg/controllers/work/apply_controller.go, pkg/controllers/work/apply_controller_test.go, pkg/utils/common.go
Fixes #
I have: add trackability for CustomResourceDefinitions
=> feat: Add CustomResourceDefinition trackability

pkg/controllers/internalmembercluster/v1beta1/member_controller.go
Fix the log error detected by my UT run: https://github.com/Azure/fleet/actions/runs/12248447322/job/34168071853?pr=975
`Observed a panic in reconciler: odd number of arguments passed as key-value pairs for logging" controller="internalmembercluster" controllerGroup="cluster.kubernetes-fleet.io" controllerKind="InternalMemberCluster" InternalMemberCluster="fleet-member-cluster-2/cluster-2" namespace="fleet-member-cluster-2" name="cluster-2" reconcileID="947855b0-ed3c-4fcd-b8bd-67fe374cd82b"`
`go.goms.io/fleet/pkg/controllers/internalmembercluster/v1beta1.(*Reconciler).Reconcile(0xc0001b1500, {0x3209350, 0xc00170df20}, {{{0xc0005d0e70, 0x16}, {0xc0013281b7, 0x9}}})
2024-12-10T02:57:46.2158543Z 	/home/runner/work/fleet/fleet/pkg/controllers/internalmembercluster/v1beta1/member_controller.go: …
=> fix: fix log error

pkg/utils/overrider/overrider.go, pkg/utils/overrider/overrider_test.go
Filter out when the override is not configured for the target placement when rolling out the resources
Fixes #
I have:
added unit test
Watching the override snapshot resources in the rollout controller will be in a separate PR
=> feat: support placement field in the override

pkg/controllers/rollout/controller.go, test/e2e/placement_cro_test.go, test/e2e/placement_ro_test.go
- watch override snapshots in the rollout controller
Fixes #
I have:
added e2e tests
=> feat: override triggers rollout

pkg/controllers/clusterresourceplacementeviction/controller.go, pkg/controllers/clusterresourceplacementeviction/controller_test.go
=> fix: use CRP defaulter to account for nil CRP policy in eviction controller

pkg/controllers/updaterun/controller.go, pkg/controllers/updaterun/controller_integration_test.go, pkg/controllers/updaterun/initialization.go, pkg/controllers/updaterun/initialization_integration_test.go, pkg/controllers/updaterun/validation.go, pkg/controllers/updaterun/validation_integration_test.go, pkg/controllers/updaterun/validation_test.go
This PR implements the `clusterStagedUpdateRun` validation
Fixes #
I have:
=> feat: implement clusterStagedUpdateRun validation

go.mod, go.sum
There is a new CVE [CVE-2024-45338](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpkg.go.dev%2Fvuln%2FGO-2024-3333&data=05%7C02%7Czhiyinglin%40microsoft.com%7Cf2abf6a1b8fc4473606c08dd206339c7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638702332846277008%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=MIGVZVHO8HDrdJanvb3DfMrnAGqZbjq1pT7nFXIdUEo%3D&reserved=0) published yesterday marked with HIGH severity. This CVE impacts the low-level library golang/x/net, which is again, widely used by most components that have network access.
This CVE affects the code path on the golang.org/x/net/html package, on the API calls Parse/ParseXXX functions. This CVE is exploitable if your code is …
=> fix: bump golang.org/x/net to v0.33.0 to mitigate CVE-2024-45338

pkg/controllers/updaterun/controller.go, pkg/controllers/updaterun/controller_integration_test.go, pkg/controllers/updaterun/execution.go, pkg/controllers/updaterun/execution_integration_test.go, pkg/controllers/updaterun/execution_test.go, pkg/controllers/updaterun/initialization_integration_test.go, pkg/controllers/updaterun/validation.go, pkg/controllers/updaterun/validation_integration_test.go, pkg/controllers/updaterun/validation_test.go
Implement clusterStagedUpdateRun execution. Also made some refactoring.
Fixes #
I have:
=> feat: implement clusterStagedUpdateRun execution

apis/cluster/v1beta1/zz_generated.deepcopy.go, apis/placement/v1/binding_types.go, apis/placement/v1beta1/binding_types.go, apis/placement/v1beta1/zz_generated.deepcopy.go, apis/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/placement.kubernetes-fleet.io_clusterresourcebindings.yaml, test/apis/v1alpha1/zz_generated.deepcopy.go
Fix empty "WORKCREATED" status when getting clusterResourceBindings:
```
NAME                          WORKCREATED   RESOURCESAPPLIED   AGE
example-placement-member1-***               True               2d22h
```
Fixes #
I have:
After the fix:
=> fix: fix empty WorkCreated status in clusterResourceBindings

apis/placement/v1alpha1/disruptionbudget_types.go, apis/placement/v1alpha1/eviction_types.go, pkg/controllers/clusterresourceplacementeviction/controller.go, pkg/controllers/clusterresourceplacementeviction/controller_test.go, pkg/utils/condition/condition.go
=> fix: handle PickFixed CRP in eviction controller

apis/placement/v1alpha1/common.go, charts/hub-agent/templates/deployment.yaml, charts/hub-agent/values.yaml, cmd/hubagent/options/options.go, cmd/hubagent/workload/setup.go, examples/stagedupdaterun/clusterStagedUpdateRun.yaml, pkg/controllers/updaterun/controller.go, pkg/controllers/updaterun/controller_integration_test.go, pkg/controllers/updaterun/execution.go, pkg/controllers/updaterun/execution_integration_test.go, pkg/controllers/updaterun/initialization.go, pkg/controllers/updaterun/initialization_integration_test.go, pkg/controllers/updaterun/validation_integration_test.go
Add the flag and conditionally enable the `clusterStagedUpdateRun` controller.
Fix a bug found during testing: the updateRun controller need to add `rolloutStarted` condition to binding too for the workgenerator to continue.
Also add an additional check during initialization to make sure a binding with old policyschedulingsnapshot is expected to be in `Unscheduled` state.
Fixes #
I have:
=> feat: enable clusterStagedUpdateRun controller

apis/placement/v1alpha1/common.go, apis/placement/v1alpha1/disruptionbudget_types.go, charts/hub-agent/templates/deployment.yaml, charts/hub-agent/values.yaml, cmd/hubagent/options/options.go, cmd/hubagent/workload/setup.go, config/crd/bases/placement.kubernetes-fleet.io_clusterresourceplacementdisruptionbudgets.yaml, config/crd/bases/placement.kubernetes-fleet.io_clusterresourceplacementevictions.yaml, test/apis/placement/v1alpha1/api_validation_integration_test.go
Fixes #
I have:
Added missing API validation IT
Ran, make manifests
=> fix: CEL validation for CRPDB and flag to disable eviction controller by default

pkg/controllers/updaterun/execution_integration_test.go, pkg/controllers/updaterun/initialization.go, pkg/controllers/updaterun/initialization_integration_test.go, pkg/controllers/updaterun/validation_integration_test.go
1. When scheduling policy is PickAll, we update PolicyObservedClusterCount to the number of scheduled/bound clusterResourceBindings, instead of -1. For PickFix and PickN, we validate if the number of bindings match the expected count.
2. Add more output in one of the integration test to help debugging UT flakes.
Fixes #
I have:
=> fix: fix stagedUpdateRun PolicyObservedClusterCount

apis/placement/v1alpha1/stagedupdate_types.go, apis/placement/v1beta1/stageupdate_types.go, config/crd/bases/placement.kubernetes-fleet.io_clusterapprovalrequests.yaml, config/crd/bases/placement.kubernetes-fleet.io_clusterstagedupdateruns.yaml, config/crd/bases/placement.kubernetes-fleet.io_clusterstagedupdatestrategies.yaml, examples/stagedupdaterun/approvalRequest.yaml, test/apis/placement/v1beta1/api_validation_integration_test.go
1. Add additionalPrinterColumns for `clusterStagedUpdateRun` and `clusterApprovalRequest` objects.
2. Add validations in updateRun name length and stageName to ensure ApprovalRequest name valid .
3. Update the examples to use the v1beta1 APIs.
The `get` command outputs now look like:
```
kubectl get clusterstagedupdaterun
NAME          PLACEMENT           RESOURCE-SNAPSHOT               POLICY-SNAPSHOT        INITIALIZED   SUCCEEDED   AGE
example-run   example-placement   example-placement-0-snapshot   example-placement-7   True          True        13m
kubectl get clsuterstagedupdaterun -owide
NAME          PLACEMENT           RESOURCE-SNAPSHOT               STRATEGY           POLICY-SNAPSHOT        INITIALIZED   SUCCEEDED   AGE
example-run   example-placement …
```
=> interface: improve ClusterStagedUpdateRun APIs

cmd/hubagent/workload/setup.go, pkg/controllers/clusterresourceplacementeviction/controller.go, pkg/controllers/clusterresourceplacementeviction/controller_test.go, pkg/controllers/clusterresourceplacementeviction/suite_test.go, test/e2e/actuals_test.go, test/e2e/enveloped_object_placement_test.go, test/e2e/join_and_leave_test.go, test/e2e/placement_cro_test.go, test/e2e/placement_eviction_test.go, test/e2e/placement_pickall_test.go, test/e2e/placement_pickfixed_test.go, test/e2e/placement_pickn_test.go, test/e2e/placement_ro_test.go, test/e2e/placement_selecting_resources_test.go, test/e2e/rollout_test.go, test/e2e/scheduler_watchers_test.go, test/e2e/setup_test.go, test/e2e/taint_toleration_test.go, test/e2e/utils_test.go, test/e2e/webhook_test.go
Fixes #
I have:
Added uncached reader for eviction controller to ensure PDB can be read directly from API server if it exists to avoid cache miss
=> test: Eviction E2E

test/e2e/placement_eviction_test.go, test/e2e/utils_test.go
=> test: remove the unnecessary test function

docs/concepts/Override/README.md, docs/howtos/cluster-resource-override.md, examples/test-cro1.yaml, examples/test-ro1.yaml
update cro docs, to add placement name, reserved variables, and delete override type
Fixes #
I have:
RO docs will be in a separate PR
=> docs: update cro docs

pkg/utils/validator/resourceoverride.go, pkg/webhook/resourceoverride/resourceoverride_validating_webhook.go, test/e2e/webhook_test.go
1 fix the resource webhook logic that didn't filter by the namespace
2. fix related flaky e2e ( https://github.com/Azure/fleet/actions/runs/12775197652/job/35611032906) which is caused by the cached list in the webhook
Fixes #
I have:
=> test: fix the resource override webhook logic and fix related flaky e2e

pkg/controllers/workapplier/availability_tracker.go, pkg/controllers/workapplier/availability_tracker_test.go, pkg/utils/common.go
Fixes #
I have: add resources to `isDataResource` for resources that don't have conditions that is related to it's availability
=> feat: add data resources availability

.github/workflows/ci.yml, .github/workflows/code-lint.yml, .github/workflows/trivy.yml, .golangci.yml, docker/hub-agent.Dockerfile, docker/member-agent.Dockerfile, docker/refresh-token.Dockerfile, go.mod
hubagent (gobinary)
Total: 3 (UNKNOWN: 0, LOW: 0, MEDIUM: 3, HIGH: 0, CRITICAL: 0)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬──────────────────────────────┬──────────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │        Fixed Version         │                            Title                             │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼──────────────────────────────┼──────────────────────────────────────────────────────────────┤
│ stdlib  │ CVE-2024-45336 │ MEDIUM   │ fixed  │ 1.22.7            │ 1.22.11, 1.23.5, 1.24.0-rc.2 │ golang: net/http: net/http: sensitive headers incorrectly    │
│         │                │          │        │ …
=> fix: bump go version to fix CVEs

apis/placement/v1alpha1/stagedupdate_types.go, apis/placement/v1beta1/stageupdate_types.go, config/crd/bases/placement.kubernetes-fleet.io_clusterstagedupdateruns.yaml, pkg/controllers/updaterun/execution.go, pkg/controllers/updaterun/initialization.go, pkg/controllers/updaterun/initialization_integration_test.go, test/e2e/actuals_test.go, test/e2e/resources_test.go, test/e2e/setup_test.go, test/e2e/updaterun_test.go, test/e2e/utils_test.go
Add e2e tests for staged update run feature.
Fixes #
I have:
=> test: stagedUpdateRun e2e tests

pkg/controllers/workapplier/controller.go, pkg/controllers/workapplier/controller_integration_migrated_test.go, pkg/controllers/workapplier/controller_integration_test.go, pkg/controllers/workapplier/status.go, pkg/controllers/workapplier/status_test.go
This PR tweaks how the new work applier sets conditions for the Work objects and their manifests.
I have:
=> feat: tweak the condition behaviors in the new work applier

pkg/controllers/rollout/controller.go, pkg/controllers/rollout/controller_integration_test.go, pkg/controllers/rollout/controller_test.go
This PR fixes an issue in the rollout controller where bindings might not receive status refresh after binding spec changes.
Specifically, when 
a) a `Bound` binding with up to date resource/override snapshot; or
b) an `Unscheduled` binding that has not been deleted yet
has its spec changed (e.g., apply strategy update), rollout controller will stop processing them and such bindings will no longer have fresh `RolloutStarted` condition added to their status. As a result, work generator will refuse to process these bindings and the system will be stuck.
I have:
- [] E2E tests will be added in a separate PR (enable the new work applier)  
N/A
=> fix: address an issue in the rollout controller where bindings might not receive status refresh after binding spec changes

pkg/controllers/overrider/clusterresource_controller.go, pkg/controllers/overrider/clusterresource_controller_integration_test.go, pkg/controllers/overrider/common.go, pkg/controllers/overrider/common_test.go, pkg/controllers/overrider/resource_controller.go, pkg/controllers/overrider/resource_controller_integration_test.go, pkg/controllers/workgenerator/override_test.go
1. fix the namespace empty with resource override list. 
2. further unify the CRO/RO flow
3. fix test issues
I have:
=> fix: fix the namespace empty with resource override list

apis/placement/v1alpha1/stagedupdate_types.go, apis/placement/v1beta1/stageupdate_types.go, config/crd/bases/placement.kubernetes-fleet.io_clusterstagedupdateruns.yaml, config/crd/bases/placement.kubernetes-fleet.io_clusterstagedupdatestrategies.yaml, test/apis/placement/v1beta1/api_validation_integration_test.go
Since waitTime is only meaningful when after-stage task type is "Timedwait", setting an unconditional default value of 1h looks confusing when type is "Approval":
```
- afterStageTasks:
- type: Approval
waitTime: 1h
```
We do have a check during initialization to make sure the value is valid when type is "Timedwait": https://github.com/Azure/fleet/blob/main/pkg/controllers/updaterun/initialization.go#L389C2-L395C3
Fixes #
I have:
=> interface: [updateRun] remove waitTime default value in afterStageTasks

docs/howtos/cluster-resource-override.md, docs/howtos/resource-override.md
- update the ro how-to docs to include new features
- reorg the structure of cro & ro docs
Fixes #
I have:
=> docs: update ro docs

examples/test-cro1.yaml, examples/test-ro1.yaml, pkg/controllers/workgenerator/override_test.go
- add documentation for the override examples
- add a UT
Fixes #
I have:
=> docs: add comment to the override examples

pkg/controllers/clusterresourceplacement/controller.go, pkg/utils/controller/controller.go, pkg/utils/controller/metrics/metrics.go
I have: add prometheus metric to show CRP completion which will be used for alerting and monitoring.
Metric includes label for CRP name. If value is "1", CRP rollout is completed. Otherwise, if value is "0", the CRP rollout is incomplete.
Once CRP is deleted, the metric will also disappear. Below I deleted the CRP "test-crp", which is no longer on the list below.
=> feat: add metric for crp completion

pkg/controllers/updaterun/controller_integration_test.go, pkg/controllers/updaterun/execution.go, pkg/controllers/updaterun/execution_integration_test.go, pkg/controllers/updaterun/initialization_integration_test.go
Fix an issue that when both Timedwait and Approval after-stage tasks are present, it might block each other: the ApprovalReq is only created after wait time has passed; the wait time check is only done when the ApprovalReq is approved.
Fixes #
I have:
=> fix: fix waitTime and approval task blocking each other

test/upgrade/after/actuals_test.go, test/upgrade/before/actuals_test.go, test/upgrade/before/setup_test.go
This PR address an inconsistency issue in upgrade tests where the tests expect a reason string from older Fleet versions while new value has taken effect
I have:
N/A
N/A
=> test: address an inconsistency in upgrade tests

apis/placement/v1alpha1/common.go, pkg/controllers/workgenerator/override.go, pkg/controllers/workgenerator/override_test.go
Allow user to use the value of an arbitrary key on the cluster as the override
example 
${MEMBER-CLUSTER-LABEL-KEY-fleet.azure.com/location-region_public} 
would be replaced by the value of the key fleet.azure.com/location-region_public on the cluster
Fixes #
I have:
=> feat: support arbitrary key on the cluster as the value of override

go.mod, go.sum, pkg/controllers/workapplier/availability_tracker.go, pkg/controllers/workapplier/availability_tracker_test.go, pkg/utils/common.go
=> feat: add svc export trackability 

docs/concepts/SafeRollout/README.md
Fixes #
I have: updated SafeRollout concept doc based on new availability trackers
=> docs: Update SafeRollout concept doc based on new availability trackers

pkg/controllers/workapplier/controller.go, pkg/controllers/workapplier/controller_integration_test.go, pkg/controllers/workapplier/preprocess.go, test/e2e/enveloped_object_placement_test.go
This PR fixes an issue where work applier will reject objects with both generate name and name set.
Note that objects with only generate name are still rejected by Fleet.
I have:
=> fix: enable the work applier to process objects with both name and generate name specified

docs/demos/ArgoCD/fleet-argocd-integration.md, docs/demos/ArgoCD/manifests/guestbook-app.yaml, docs/demos/ArgoCD/manifests/guestbook/member1/test-configmap.yaml, docs/demos/ArgoCD/manifests/guestbook/member2/test-configmap.yaml, docs/demos/ArgoCD/manifests/guestbook/member3/test-configmap.yaml, test/e2e/enveloped_object_placement_test.go, test/e2e/utils_test.go, test/upgrade/before/scenarios_test.go, test/upgrade/before/utils_test.go
Fix an e2e bug, the test didn't clean up the resources from the hub cluster.
Also fix a typo in the argocd demo doc just found :)
Fixes #
I have:
=> test: fix e2e namespace already exist issue

pkg/controllers/workgenerator/controller.go, test/e2e/placement_cro_test.go, test/e2e/placement_ro_test.go
Requeue the request when the override has been changed but the resource has not been changed.
Otherwise, the CRP will stuck in ApplyInProcess
Fixes #
I have:
Added e2e tests
=> fix: requeue the request when the override has been changed

docs/howtos/eviction-placement-disruption-budget.md
=> docs: minor update to use pickN CRP for eviction how-to doc

pkg/controllers/workapplier/apply.go, pkg/controllers/workapplier/availability_tracker.go, pkg/controllers/workapplier/controller_integration_test.go, pkg/controllers/workapplier/controller_test.go, pkg/controllers/workapplier/preprocess.go, pkg/controllers/workapplier/process.go, pkg/controllers/workapplier/status.go, test/e2e/placement_negative_cases_test.go
This PR fixes the bug where the work applier would stop processing manifests if one of them fails the pre-processing stage.
Fixes #
I have:
=> fix: address the issue work applier has after disabling parallelism + add more log entries

pkg/controllers/workapplier/status.go
fix the agent log format and test the Kaito PR agent
Fixes #
I have:
=> fix: fix the agent log format

pkg/controllers/updaterun/controller.go, pkg/controllers/updaterun/controller_integration_test.go, pkg/controllers/updaterun/execution.go, pkg/controllers/updaterun/execution_integration_test.go, pkg/controllers/updaterun/validation_integration_test.go, test/e2e/actuals_test.go
When updateRun or a stage completes (either succeeds or fails), set progressing condition to false.
Also add missing condition messages.
Fixes #
I have:
=> fix: set updaterun progressing condition to false when finished

.github/workflows/ci.yml, .github/workflows/code-lint.yml, .github/workflows/trivy.yml, .github/workflows/upgrade.yml, .golangci.yml, docker/hub-agent.Dockerfile, docker/member-agent.Dockerfile, docker/refresh-token.Dockerfile, go.mod
Fixing CVEs,
- CVE-2024-45336
- CVE-2024-45341
- CVE-2025-22866
I have:
=> fix: bump go version to 1.23.6 for CVE

pkg/utils/common.go, pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook.go, pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook_test.go
Currently the fleet guard rail prevents users from creating namespaces with fleet/kube prefix instead of fleet-/kube- prefix.
This PR fixes that issue and I moved some code around to reuse code.
Eg: fleettest, kubetest namespaces will be prevented from being created which is not ideal
Fixes #
I have:
=> fix: use fleet-/kube- prefix checks in fleet guard rail

pkg/webhook/membercluster/membercluster_validating_webhook.go, pkg/webhook/webhook.go, test/e2e/fleet_guard_rail_test.go, test/e2e/join_and_leave_test.go
deny the member leave when member still has serviceExport in the webhook
Fixes #
I have:
=> feat: deny the member leave when member still has serviceExport

.github/workflows/codespell.yml, pkg/controllers/rollout/controller.go, pkg/controllers/rollout/controller_integration_test.go, pkg/controllers/workgenerator/controller.go, pkg/controllers/workgenerator/controller_integration_test.go, pkg/controllers/workgenerator/controller_test.go, pkg/controllers/workgenerator/manifests/resourcequota2.yaml, pkg/controllers/workgenerator/manifests/test-envelop-configmap.yaml, pkg/controllers/workgenerator/manifests/test-envelop-configmap2.yaml, pkg/controllers/workgenerator/suite_test.go, test/e2e/actuals_test.go, test/e2e/enveloped_object_placement_test.go, test/e2e/join_and_leave_test.go, test/e2e/placement_cro_test.go, test/e2e/placement_ro_test.go, test/e2e/resources/test-envelop-configmap.yaml
=> chore: backport from kubefleet

pkg/webhook/add_handler.go, pkg/webhook/managedresource/managedresource_validating_webhook.go, pkg/webhook/managedresource/managedresource_validating_webhook_test.go, pkg/webhook/validation/uservalidation.go, pkg/webhook/webhook.go, pkg/webhook/webhook_test.go, test/e2e/resources_test.go, test/e2e/utils_test.go, test/e2e/webhook_test.go
Fixes :
Enable the fleet dataplane to deny any create/update/delete operations on ARM managed resources.  At the moment, CRP, Namespace, ResourceQuota, and NetworkPolicy can be managed resources.
I have:
`make local-unit-test` ran successfully
=> feat: add managed resource webhook

docker/crd-installer.Dockerfile, docker/hub-agent.Dockerfile, docker/member-agent.Dockerfile, docker/refresh-token.Dockerfile
=> chore: use base distroless images from MCR

.github/workflows/build-publish-mcr.yml
This PR updates the build push mcr pipeline to avoid having an additional parameter for Arc Extension and rather use the fleet agent version as the version to package the helm charts. This PR strips the v because the package version must follow SemVer.
Fixes #
I have:
=> fix: Use fleet agent version as arc version

.github/workflows/codespell.yml, cmd/memberagent/main.go, pkg/controllers/placement/resource_selector.go, pkg/controllers/workgenerator/envelope.go, pkg/propertyprovider/azure/controllers/node.go, pkg/propertyprovider/azure/controllers/pod.go, pkg/propertyprovider/azure/provider.go, pkg/propertyprovider/azure/provider_integration_test.go, pkg/propertyprovider/azure/provider_test.go, pkg/propertyprovider/azure/suite_test.go, pkg/propertyprovider/azure/trackers/nodes.go, pkg/propertyprovider/azure/trackers/trackers_test.go, test/e2e/actuals_test.go, test/e2e/resource_placement_negative_cases_test.go
Fixes #
I have:
3f786157 (cncf/main) chore: bump step-security/harden-runner from 2.13.0 to 2.13.1 (#250)
b98cb4c3 feat: add feature gate support and gate property provider capabilities (#181)
fa46b145 feat: update the comments regarding resource sort orders in CRP/RP controller and work generator (#243)
7b21fdd3 test: add negative tests for RP (#242)
=> feat: Backport changes from KubeFleet (09/16/2025) 

.github/workflows/build-publish-mcr.yml
This PR fixes a minor issue (privileges) in the ARM64 image build pipeline.
I have:
N/A
N/A
=> fix: fixed a minor issue in ARM64 build pipeline

.github/workflows/build-publish-mcr.yml
This PR addresses a minor issue (privileges) in the ARM64 image build pipeline.
I have:
N/A
N/A
=> fix: address a minor issue in the ARM64 image build pipeline

.github/workflows/build-publish-mcr.yml
This PR addresses access issues in the ARM64 image build pipeline.
It includes a leftover commit from prev. PR.
I have:
N/A
N/A
=> fix: address access issues in the ARM64 image build pipeline

.codespellignore, cmd/crdinstaller/main.go, cmd/crdinstaller/utils/util.go, cmd/crdinstaller/utils/util_test.go, cmd/hubagent/main.go, pkg/controllers/internalmembercluster/v1beta1/member_controller.go, pkg/webhook/managedresource/createordelete.go, pkg/webhook/managedresource/createordelete_test.go, pkg/webhook/managedresource/validatingadmissionpolicy.go, pkg/webhook/managedresource/validatingadmissionpolicy_test.go, test/e2e/framework/cluster.go, test/e2e/managed_resource_vap_test.go, test/e2e/setup_test.go
Move the managed resource VAP and its binding installation out of CRD installer.  They are now installed by the hub and member agents.  For hub, they are installed after the hub agent starts and never removed.  For member, they are installed during member join and removed during member leave.
Fixes # N/A
I have:
Unit tests and E2E tests.
=> fix: move managed resource VAP out of CRDinstaller
