apis/v1/binding_types.go
apis/v1/commons.go
apis/v1/policySnapshot_types.go
apis/v1/resourceSnapshot_types.go

Update the api comments and clean up the code a bit
Fixes #
I have:

fix: clean up api comments

---

pkg/controllers/clusterresourceplacement/clusterresourceplacement_controller.go
pkg/controllers/clusterresourceplacement/clusterresourceplacement_controller_test.go

fix the master broken
Fixes #
I have:
UT

fix: fix crp controller & its unit tests

---

pkg/scheduler/framework/framework.go
pkg/scheduler/framework/framework_test.go
pkg/scheduler/framework/frameworkutils.go

It features parts of the scheduler framework logic.
I have:

feat: scheduler (8/): add more scheduler framework logic

---

pkg/scheduler/framework/dummyplugin_test.go
pkg/scheduler/framework/profile_test.go

This PR adds a dummy plugin struct for scheduler framework testing.
N/A

test: add dummy plugin for scheduler framework testings

---

apis/placement/v1beta1/zz_generated.deepcopy.go
apis/v1alpha1/zz_generated.deepcopy.go
test/e2e/e2e_test.go
test/e2e/utils/helper.go
test/e2e/webhook_test.go

test: fix E2E flakiness

---

apis/placement/v1beta1/clusterresourceplacement_types.go
pkg/controllers/clusterresourceplacement/clusterresourceplacement_controller.go
pkg/controllers/clusterresourceplacement/clusterresourceplacement_controller_test.go
pkg/controllers/clusterresourceplacement/placement_controller.go

delete all the policy snapshots & resource snapshots when CRP is in the deleting state
Fixes #
I have:
added UT

feat: handle delete for CRP controller

---

pkg/scheduler/framework/framework.go
pkg/scheduler/framework/framework_test.go

This PR adds more tests to the scheduler framework
I have:
N/A

test: add more tests to scheduler framework

---

pkg/scheduler/framework/framework_test.go

This PR fixes a flaky test for framework.
I have:
N/A
N/A

fix: flaky framework test

---

apis/placement/v1beta1/clusterresourceplacement_types.go
apis/placement/v1beta1/policysnapshot_types.go
pkg/controllers/clusterresourceplacement/controller.go
pkg/controllers/clusterresourceplacement/controller_test.go
pkg/controllers/clusterresourceplacement/placement_controllerv1alpha1.go

build the CRP status
Fixes #
I have:
UT
The PR is only to build the status and updating CRP will be in a separate PR.
appliedCondition for both CRP status & resourcePlacementStatus by collecting work status will be in a separate PR.

feat: build crp status based on policySnapshot & resourceSnapshot

---

Makefile
apis/placement/v1beta1/binding_types.go
apis/placement/v1beta1/commons.go
apis/placement/v1beta1/resourcesnapshot_types.go
config/crd/bases/placement.azure.com_clusterresourcebindings.yaml
config/crd/bases/placement.azure.com_clusterresourcesnapshots.yaml
pkg/controllers/memberclusterplacement/membercluster_controller.go
pkg/controllers/workgenerator/controller.go
pkg/controllers/workgenerator/controller_integration_test.go
pkg/controllers/workgenerator/controller_test.go
pkg/controllers/workgenerator/suite_test.go
pkg/utils/controller/controller_test.go

- Add parentResource label
- Handle resourceSnapshot not found
- Add more test
Fixes #
I have:

fix: improve work generator

---

pkg/scheduler/framework/plugins/topologyspreadconstraints/utils.go
pkg/scheduler/framework/plugins/topologyspreadconstraints/utils_test.go

This PR adds more tests to the topology spread constraints plugin.
I have:
N/A
A minor part of this PR overlaps with another test PR.

test: add more tests to topology spread constraints plugin

---

pkg/scheduler/framework/plugins/topologyspreadconstraints/plugin.go
pkg/scheduler/framework/plugins/topologyspreadconstraints/plugin_test.go
pkg/scheduler/framework/plugins/topologyspreadconstraints/utils.go
pkg/scheduler/framework/score.go
pkg/scheduler/framework/score_test.go

This PR adds more tests to the topology spread constraints plugin.
I have:
N/A
A minor part of this PR overlaps with another test PR.

test: add more tests to topology spread constraints plugin (again)

---

pkg/scheduler/framework/plugins/clusteraffinity/filtering.go
pkg/scheduler/framework/plugins/clusteraffinity/filtering_test.go
pkg/scheduler/framework/plugins/clusteraffinity/plugin.go
pkg/scheduler/framework/plugins/clusteraffinity/scoring.go
pkg/scheduler/framework/plugins/clusteraffinity/scoring_test.go
pkg/scheduler/framework/plugins/clusteraffinity/state.go

minor fixes for the clusteraffinity plugin
unit tests

refactor: shorten the variable name and add the copyright header

---

pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook.go
pkg/webhook/validation/uservalidation.go
pkg/webhook/validation/uservalidation_test.go
pkg/webhook/webhook.go
test/e2e/webhook_test.go

feat: webhook to handle label update for MC

---

pkg/scheduler/framework/plugins/sameplacementaffinity/filtering.go
pkg/scheduler/framework/plugins/sameplacementaffinity/filtering_test.go
pkg/scheduler/framework/plugins/sameplacementaffinity/plugin.go

- add sameplacementantiaffinity plugin and implement the filter extension point
Fixes #
I have:
Added unit tests
Scoring will be sent out in a separate PR.

feat: add the sameplacementaffinity plugin (filtering)

---

pkg/scheduler/framework/plugins/sameplacementaffinity/plugin.go
pkg/scheduler/framework/plugins/sameplacementaffinity/scoring.go
pkg/scheduler/framework/plugins/sameplacementaffinity/scoring_test.go

- add scoring of the sameplacementaffinity plugin
Fixes #
I have:
Added UT

feat: add sameplacementaffinity plugin (scoring)

---

charts/hub-agent/templates/deployment.yaml
charts/hub-agent/values.yaml
cmd/hubagent/main.go
cmd/hubagent/options/options.go
pkg/webhook/webhook.go
pkg/webhook/webhook_test.go

feat: flag for enableDenyWebhook

---

apis/placement/v1beta1/binding_types.go
apis/placement/v1beta1/clusterresourceplacement_types.go
apis/placement/v1beta1/default.go
cmd/hubagent/main.go
cmd/hubagent/workload/setup.go
go.mod
pkg/controllers/resourcechange/resourcechange_controller.go
pkg/controllers/rollout/controller.go
pkg/controllers/rollout/controller_integration_test.go
pkg/controllers/rollout/controller_test.go
pkg/controllers/rollout/manifests/test-cloneset.yaml
pkg/controllers/rollout/manifests/test-configmap.yaml
pkg/controllers/rollout/manifests/test_clonesets_crd.yaml
pkg/controllers/rollout/manifests/test_namespace.yaml
pkg/controllers/rollout/manifests/test_pdb.yaml
pkg/controllers/rollout/suite_test.go
pkg/utils/validator/clusterresourceplacement.go
pkg/utils/validator/clusterresourceplacement_test.go
test/integration/suite_test.go

- Rollout controller implemenation
- IT Test
Fixes #
I have:
Mostly IT

feat: Rollout controller

---

pkg/controllers/clusterresourceplacement/controller.go
pkg/controllers/workgenerator/controller.go
pkg/scheduler/framework/framework.go
pkg/utils/annotations/annotations.go
pkg/utils/annotations/annotations_test.go
pkg/utils/common.go
pkg/utils/labels/labels.go
pkg/utils/labels/labels_test.go
pkg/utils/works/works.go

- The utils will be used by both crp controller & work generator controller.
- Refactored the code related to parsing annotation & labels and would like to get rid of "utils" package as it is not a good name 
Fixes #
I have:
Will add UT once the implementation is completed.

feat: add work build status utils

---

pkg/scheduler/framework/framework.go
pkg/scheduler/profile/profile.go
pkg/scheduler/watchers/clusterschedulingpolicysnapshot/controller.go

Create a default profile for the scheduler
Fixes #
I have:

feat: add default plugin list

---

pkg/scheduler/framework/framework.go
pkg/scheduler/framework/frameworkutils.go

We added a new type for a fixed set of clusters.
- Updated the code to use the new type.
- Refactored the code to use the new terminology.
Fixes #
I have:

fix: check the placement type value instead of checking clusterNames

---

apis/placement/v1beta1/zz_generated.deepcopy.go
pkg/controllers/rollout/controller.go
pkg/controllers/work/manager.go
pkg/controllers/workgenerator/controller.go
pkg/controllers/workgenerator/controller_integration_test.go
pkg/controllers/workgenerator/controller_test.go
pkg/utils/condition/condition.go
pkg/utils/condition/condition_test.go

update the binding applied status based on the work applied status
Fixes #
I have:

feat: add the applied status in binding

---

apis/placement/v1beta1/clusterresourceplacement_types.go
pkg/controllers/clusterresourceplacement/controller.go
pkg/controllers/clusterresourceplacement/placement_status.go
pkg/controllers/clusterresourceplacement/placement_status_test.go

address the comments on #472 
Fixes #
I have:

fix: minor fixes on the CRP status

---

pkg/controllers/clusterresourceplacement/controller.go
pkg/controllers/clusterresourceplacement/controller_test.go
pkg/controllers/clusterresourceplacement/placement_status_test.go

- add events for the crp 
- update crp status
- add logs
Fixes #
I have:
UT
need to add more integration tests

feat: add events for the crp and update crp status

---

cmd/hubagent/workload/setup.go
pkg/controllers/clusterresourceplacement/placement_controllerv1alpha1.go

init required uncachedreader for the v1beta1 reconciler.
Fixes #
I have:

fix: init the uncachedreader in the main func

---

pkg/scheduler/framework/framework_test.go

This PR adds some unit tests, previously skipped for size control reasons, to the scheduler framework.
I have:
N/A

test: add some unit tests to scheduler framework

---

pkg/controllers/clusterresourceplacement/controller.go
pkg/controllers/clusterresourceplacement/placement_status.go

This PR fixes an issue where scores pointers, rather than their values, are printed out in the CRP status.
I have:
N/A

fix: report scores correctly in CRP status

---

pkg/scheduler/watchers/clusterresourceplacement/controller_integration_test.go

fix a bug in #489 
Fixes #
I have:

fix: fix the typo in scheduler crp integration tests

---

pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook.go
pkg/webhook/validation/uservalidation.go
pkg/webhook/validation/uservalidation_test.go
pkg/webhook/webhook.go
pkg/webhook/webhook_test.go
test/e2e/webhook_test.go

Fixes #
I have:
Handled first two bullet points in this PR. Will handle third point in a different PR

feat: Webhook for reserved namespaces

---

cmd/hubagent/options/options.go

feat: enable guard rail for RP testing

---

apis/placement/v1beta1/work_types.go
cmd/memberagent/main.go
pkg/controllers/clusterresourceplacement/work_propagation.go
pkg/controllers/internalmembercluster/v1alpha1/member_controller.go
pkg/controllers/internalmembercluster/v1alpha1/member_controller_integration_test.go
pkg/controllers/internalmembercluster/v1beta1/member_controller.go
pkg/controllers/internalmembercluster/v1beta1/member_controller_integration_test.go
pkg/controllers/workv1alpha1/applied_work_syncer.go
pkg/controllers/workv1alpha1/applied_work_syncer_integration_test.go
pkg/controllers/workv1alpha1/applied_work_syncer_test.go
pkg/controllers/workv1alpha1/apply_controller.go
pkg/controllers/workv1alpha1/apply_controller_helper_test.go
pkg/controllers/workv1alpha1/apply_controller_integration_test.go
pkg/controllers/workv1alpha1/apply_controller_test.go
pkg/controllers/workv1alpha1/manager.go
pkg/controllers/workv1alpha1/owner_reference_util.go
pkg/controllers/workv1alpha1/patch_util.go
pkg/controllers/workv1alpha1/patch_util_test.go
pkg/controllers/workv1alpha1/suite_test.go
test/e2e/work_api_e2e_test.go
test/integration/cluster_placement_test.go

Will use the pkg/controllers/work for v1beta1 controller and will send out in a separate PR.
Fixes #
I have:
no compile errors

refactor: move the work controller to v1alpha1

---

charts/hub-agent/templates/deployment.yaml
charts/member-agent/templates/deployment.yaml
charts/member-agent/values.yaml

This PR fixes a minor issue in hub agent chart + enables API version params in member agent chart.
I have:
N/A

fix: address a minor issue in hub agent chart + enable API version params in member agent chart

---

.pipeline/component-governance-detection.yaml

Fix component governance pipeline
Fixes #
I have:
try and error

fix: component governance pipeline

---

test/e2e/utils/helper.go
test/e2e/webhook_test.go

Fixes #
I have:
Using BeforeEach, AfterEach blocks to setup resources for MC and IMC fleet guard rail E2Es.

test: Refactor MC, IMC webhook E2Es to use BeforeEach, AfterEach

---

apis/placement/v1beta1/appliedwork_types.go
apis/placement/v1beta1/work_types.go
pkg/controllers/work/applied_work_syncer.go
pkg/controllers/work/applied_work_syncer_integration_test.go
pkg/controllers/work/applied_work_syncer_test.go
pkg/controllers/work/apply_controller.go
pkg/controllers/work/apply_controller_helper_test.go
pkg/controllers/work/apply_controller_integration_test.go
pkg/controllers/work/apply_controller_test.go
pkg/controllers/work/manager.go
pkg/controllers/work/owner_reference_util.go
pkg/controllers/work/patch_util.go
pkg/controllers/work/patch_util_test.go
pkg/controllers/work/suite_test.go

Copy the workv1alpha1 and update the code to use the v1beta1 work API instead
Fixes #
I have:
The v1beta1 work controller will be initialized in the next PR.

feat: add v1beta1 work controller

---

test/e2e/webhook_reserved_namespace_resources_test.go
test/e2e/webhook_test.go

test: Use random resource names & move resources under reserved namespaces E2Es

---

pkg/controllers/clusterresourceplacement/resource_selector.go
pkg/utils/controller/controller.go

So that we can create the monitoring based on these logs
Fixes #
I have:

feat: add formalized log in order to setup the dashboard

---

test/e2e/webhook_reserved_namespace_resources_test.go

Fixes #
I have:
E2E tests for name spaced resources:
autoscaling/v2 - horizontal pod auto scalers
coordination.k8s.io/v1 - leases
discovery.k8s.io/v1 - end point slices

test: Webhook for Namespaced resources E2E tests part 2

---

pkg/controllers/clusterresourceplacement/controller_test.go
pkg/controllers/clusterresourceplacement/placement_status.go
pkg/controllers/workgenerator/controller.go
pkg/controllers/workgenerator/controller_integration_test.go
pkg/controllers/workgenerator/controller_test.go
pkg/utils/labels/labels.go
pkg/utils/labels/labels_test.go

This PR fixes an issue where the new forked Work API is not used in related controllers.
Fixes #
I have:
N/A

fix: enable the new forked Work API in related controllers

---

pkg/authtoken/providers/azure/azure_msi.go

Need to log the scope for debug purpose
Fixes #
I have:

fix: add scope in the log when fail to get token

---

test/e2e/webhook_reserved_namespace_resources_test.go

Fixes #
I have:
Will be merged after #512
networking.k8s.io/v1 - Ingress
policy/v1 - PodDisruptionBudgets
storage.k8s.io/v1 - CSIStorageCapacities

test: Webhook for Namespaced resources E2Es part 3

---

charts/hub-agent/templates/crds/placement.kubernetes-fleet.io_works.yaml
charts/member-agent/templates/crds/placement.kubernetes-fleet.io_appliedworks.yaml
cmd/memberagent/main.go

This PR fixes an issue where the new forked Work API is not even enabled in member agent.
I have:
N/A
N/A

fix: enable the new forked Work API in member agent

---

pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook.go
pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook_test.go
pkg/webhook/validation/uservalidation.go
test/e2e/webhook_test.go

feat: Webhook for Event

---

pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook.go
pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook_test.go
pkg/webhook/validation/uservalidation.go
pkg/webhook/validation/uservalidation_test.go
test/e2e/webhook_reserved_namespace_resources_test.go
test/e2e/webhook_test.go

feat: Improve logs, UTs and readability for fleet guard rail

---

cmd/hubagent/workload/setup.go
pkg/controllers/clusterresourceplacement/controller.go
pkg/controllers/clusterresourceplacement/controller_integration_test.go
pkg/controllers/clusterresourceplacement/placement_status.go
pkg/controllers/clusterresourceplacement/suite_test.go
pkg/controllers/clusterschedulingpolicysnapshot/controller.go
pkg/controllers/clusterschedulingpolicysnapshot/controller_integration_test.go
pkg/controllers/clusterschedulingpolicysnapshot/suite_test.go

- add basic integration tests
Fixes #
I have:
IT

test: add basic integration test for crp

---

pkg/controllers/rollout/controller.go

This PR fixes an issue where rollout controller will panic when processing CRPs of the PickFixed placement type, as such CRPs do not have numOfClusters field set.
I have:

fix: address an issue where rollout controller will panic when processing CRPs of the PickFixed placement type

---

test/e2e/actuals_test.go
test/e2e/placement_selecting_resources_test.go
test/e2e/placement_test.go
test/e2e/resources_test.go
test/e2e/utils_test.go

add basic selecting resource related e2e tests
Fixes #
I have:
more tests will be added in the next PR

test: add selecting resource related e2e tests

---

pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook.go
pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook_test.go
test/e2e/v1alpha1/webhook_test.go

Fixes #
I have:
Original PR: https://github.com/Azure/fleet/pull/543

fix: handle Work, IMC, event request correctly

---

pkg/utils/validator/clusterresourceplacement.go
pkg/utils/validator/clusterresourceplacement_test.go

feat: v1beta1 CRP name length validation

---

pkg/utils/validator/clusterresourceplacement.go
pkg/utils/validator/clusterresourceplacement_test.go
pkg/webhook/clusterresourceplacement/v1alpha1_clusterresourceplacement_validating_webhook.go
pkg/webhook/clusterresourceplacement/v1beta1_clusterresourceplacement_validating_webhook.go
test/e2e/utils_test.go
test/e2e/webhook_test.go

feat: v1beta1 CRP Validation for PickFixed Placement Policy

---

apis/cluster/v1beta1/zz_generated.deepcopy.go
apis/placement/v1beta1/zz_generated.deepcopy.go
apis/v1alpha1/zz_generated.deepcopy.go
pkg/controllers/membercluster/v1beta1/membercluster_controller.go
pkg/controllers/membercluster/v1beta1/membercluster_suite_test.go
pkg/controllers/rollout/controller_integration_test.go

improve the log in the member cluster controller
Fixes #
I have:

fix: improve the log in the member cluster controller

---

pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook_test.go
pkg/webhook/validation/uservalidation.go
pkg/webhook/validation/uservalidation_test.go
test/e2e/v1alpha1/webhook_reserved_namespace_resources_test.go
test/e2e/v1alpha1/webhook_test.go

fix: Print GVK instead of Kind for guard rail logs

---

cmd/memberagent/main.go

Removed startErr which is never printed and changed the log level.
Fixes #
I have:

fix: change the log level and add err log for starting/stopping controller manager

---

pkg/utils/validator/clusterresourceplacement.go
pkg/utils/validator/clusterresourceplacement_test.go
test/e2e/webhook_test.go

feat: v1beta1 CRP validation for PickN Placement Policy

---

apis/placement/v1beta1/resourcesnapshot_types.go
pkg/controllers/clusterresourceplacement/controller.go
pkg/controllers/clusterresourceplacement/controller_integration_test.go
pkg/controllers/clusterresourceplacement/controller_test.go
pkg/controllers/clusterresourceplacement/placement_status.go
pkg/controllers/clusterresourceplacement/resource_selector.go
pkg/utils/annotations/annotations.go
pkg/utils/annotations/annotations_test.go
test/e2e/README.md
test/e2e/actuals_test.go
test/e2e/enveloped_object_placement_test.go
test/e2e/resources/resourcequota.yaml
test/e2e/resources/test-cloneset.yaml
test/e2e/resources/test-configmap.yaml
test/e2e/resources/test-envelop-configmap.yaml
test/e2e/resources/test-service.yaml
test/e2e/resources/test_clonesets_crd.yaml
test/e2e/resources/webhook.yaml
test/e2e/resources_test.go
test/e2e/setup.sh
test/e2e/setup_test.go
test/e2e/utils_test.go

add the envelop object annotation to the master resource snapshot to support extra work for enveloped objects.
Fixes #
I have:
UT/E2E

feat: add the envelop object annotation to support extra work for enveloped objects

---

go.mod
go.sum
pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook.go
pkg/webhook/validation/uservalidation.go
test/e2e/v1alpha1/README.md
test/e2e/v1alpha1/e2e_test.go
test/e2e/v1alpha1/manifests/internalserviceexport-crd.yaml
test/e2e/v1alpha1/webhook_test.go

feat: Allow fleet networking resources

---

pkg/scheduler/framework/uniquename/uniquename.go
pkg/scheduler/framework/uniquename/uniquename_test.go
pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook.go

limit binding name length to 63 since it needs to be used by the work as a label value.
Fixes #
I have:

fix: limit binding name length to 63

---

apis/placement/v1beta1/binding_types.go
config/crd/bases/placement.kubernetes-fleet.io_clusterresourcebindings.yaml

fix binding CRD status
Fixes #
I have:

fix: fix binding CRD

---

pkg/controllers/membercluster/v1alpha1/membercluster_controller.go
pkg/controllers/membercluster/v1beta1/membercluster_controller.go

Replace cmp package with reflect package in production code. Mostly used to compare.
Fixes #
I have:

fix: Replace cmp package with reflect package in production code

---

pkg/controllers/clusterresourceplacement/controller.go
pkg/controllers/clusterresourceplacement/placement_status_test.go
test/e2e/placement_updating_members_test.go

Not enqueue the request when scheduler has not selected any cluster.
Fixes #
I have:
add e2e test

fix: improve CRP requeue

---

pkg/utils/validator/clusterresourceplacement.go
pkg/utils/validator/clusterresourceplacement_test.go
pkg/webhook/clusterresourceplacement/v1beta1_clusterresourceplacement_validating_webhook.go
test/e2e/webhook_test.go

feat: Add check to ensure CRP placement type is immutable

---

docs/howtos/README.md
docs/howtos/crp.md

This PR updates the README file for how-to guides.
I have:
N/A
N/A

docs: update the README file for how-to guides

---

pkg/webhook/validation/uservalidation_test.go

test: fix failing pretty print UT

---

docs/howtos/crp.md

rephase crp desc
Fixes #
I have:

fix: rephase crp desc

---

test/e2e/stop.sh

This PR fixes a minor issue in `stop.sh`.
I have:
N/A
N/A

fix: a minor issue in stop.sh for stopping E2E environment

---

docs/howtos/clusters.md
hack/membership/join.sh

This PR adds a how-to guide for managing clusters.
I have:
N/A
N/A

docs: add a how-to guide for cluster management

---

docs/concepts/MemberCluster/README.md
docs/concepts/README.md
docs/howtos/README.md

add membercluster doc and update the index

docs: add membercluster concept doc

---

pkg/webhook/webhook.go

add webhook calling timeout
Fixes #
I have:

fix: add webhook calling timeout

---

pkg/webhook/webhook.go
test/e2e/v1alpha1/webhook_reserved_namespace_resources_test.go
test/e2e/v1alpha1/webhook_test.go

Fixes #
I have:
Not monitoring leases, events. Tried adding E2E for local subject access review object but faced trouble creating object

feat: fleet guard rail static GVK list for namespaced resources

---

docs/troubleshooting/README.md

docs: Troubleshooting guide

---

test/e2e/placement_selecting_resources_test.go

test: fix flaky CRP E2E

---

pkg/controllers/clusterresourceplacement/controller.go
pkg/controllers/clusterresourceplacement/controller_integration_test.go
pkg/controllers/clusterresourceplacement/placement_status_test.go
test/e2e/actuals_test.go
test/e2e/enveloped_object_placement_test.go
test/e2e/placement_pickall_test.go
test/e2e/placement_pickfixed_test.go
test/e2e/placement_pickn_test.go
test/e2e/placement_selecting_resources_test.go
test/e2e/scheduler_watchers_test.go
test/e2e/utils_test.go

feat: set observedResourceIndex for CRP status

---

docs/howtos/clusters.md
hack/membership/join.sh

This PR fixes an issue where users that choose to not build their own images might have trouble pulling images when following our docs.
I have:
N/A
N/A

fix: use the Always pull policy in the general docs

---

docs/howtos/affinities.md
docs/howtos/crp.md
docs/howtos/topology-spread-constraints.md

Fixes some yaml examples due to some typos or errors
Fixes #
I have:

docs: Fix some examples in docs

---

apis/placement/v1beta1/zz_generated.deepcopy.go
test/e2e/scheduler_watchers_test.go

This PR adds a few more test cases for the scheduler watchers.
I have:
N/A
N/A

test: add more E2E tests (6/): scheduler watchers (2/) 

---

pkg/controllers/clusterresourceplacement/controller.go
pkg/controllers/clusterresourceplacement/controller_test.go
pkg/controllers/clusterresourceplacement/placement_status_test.go
pkg/controllers/rollout/controller.go

feat: handle multiple resource snapshots - split selected resources into lists

---

pkg/controllers/rollout/controller_integration_test.go

Fixes #
I have: Fixed flaky rollout controller integration test

fix: fix flaky rollout controller integration test

---

docs/getting-started/kind.md

This PR adds a getting started tutorial for using Fleet with kind clusters.
I have:
N/A
N/A

docs: add getting started tutorial (kind)

---

Makefile
README.md
test/e2e/setup.sh

upgrade test env to 1.28
Fixes #
I have:

fix: upgrade upstream test env to 1.28.0

---

pkg/controllers/internalmembercluster/v1beta1/member_controller.go
pkg/controllers/membercluster/v1beta1/membercluster_controller.go
pkg/controllers/work/apply_controller.go

Add latency log for controllers
Fixes #
I have:

fix: add latency log for controllers

---

pkg/scheduler/framework/framework.go

Update the binding changes in parallel to improve performance when many clusters are picked.
Fixes #
I have:

perf: Update the binding changes in parallel to improve performance when many clusters are picked.

---

pkg/scheduler/framework/framework.go

Add some comments and return wrapped error.
Fixes #
I have:
Existing UT

fix: address previous comments

---

cmd/hubagent/main.go
cmd/hubagent/options/options.go
cmd/hubagent/workload/setup.go
pkg/controllers/membercluster/v1beta1/membercluster_controller.go
pkg/controllers/rollout/controller.go
pkg/controllers/workgenerator/controller.go

Add an option to increase the concurrency of the controller downstream of scheduler.
Fixes #
I have:

perf: increase controller concurrency

---

config/crd/bases/placement.kubernetes-fleet.io_overriddenclusterresources.yaml

Fixes #
I have:
Couldn't find the golang object for OverridenClusterResource

fix: CRD version for OverridenClusterResource

---

pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook.go
pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook_test.go
pkg/webhook/validation/uservalidation.go
test/e2e/fleet_guard_rail_test.go

feat: Allow taints to be updated for v1beta1 MC

---

pkg/controllers/resourcechange/resourcechange_controller.go
pkg/controllers/resourcechange/resourcechange_controller_test.go

fix: resource selector uses name or label selector

---

pkg/controllers/clusterresourceplacement/resource_selector.go
pkg/controllers/clusterresourceplacement/resource_selector_test.go
pkg/utils/common.go
pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook.go
pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook_test.go
pkg/webhook/validation/uservalidation.go
pkg/webhook/validation/uservalidation_test.go
test/e2e/v1alpha1/webhook_test.go
test/e2e/v1alpha1/work_load_test.go
test/integration/cluster_placement_test.go

Fixes #
I have: improve member clusters member agent by ensuring the resources are sorted to have the Namespace and CustomResourceDefinition be before other selected Resources. I have also added a unit test to verify the resources were sorted correctly.

perf: improve member cluster member agent

---

pkg/controllers/clusterresourceplacement/cluster_selector.go
pkg/controllers/clusterresourceplacement/work_propagation.go
pkg/controllers/memberclusterplacement/membercluster_controller.go
pkg/resourcewatcher/change_dector.go
pkg/utils/apiresources.go
pkg/utils/common.go
pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook.go
pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook_test.go

fix: reorganize GVK/GVR list

---

pkg/controllers/clusterresourceplacement/controller.go
pkg/controllers/clusterresourceplacement/controller_integration_test.go
pkg/controllers/clusterresourceplacement/work_propagation.go
pkg/controllers/work/apply_controller.go
pkg/utils/resource/resource.go
pkg/utils/resource/resource_test.go

Remove duplicate code
Fixes #
I have:

refactor: create hashOf func

---

pkg/utils/validator/clusterresourceplacement.go
pkg/utils/validator/clusterresourceplacement_test.go
pkg/webhook/clusterresourceplacement/v1beta1_clusterresourceplacement_validating_webhook.go
test/e2e/webhook_test.go

feat: validate tolerations

---

README.md
examples/fleet_v1beta1_membercluster.yaml
pkg/utils/validator/clusterresourceplacement.go
pkg/utils/validator/clusterresourceplacement_test.go
pkg/webhook/clusterresourceplacement/v1beta1_clusterresourceplacement_validating_webhook.go
test/e2e/webhook_test.go

Fixes #
I have:
We only allow tolerations to be added to CRP. Existing tolerations cannot be updated or deleted.

feat: deny update/delete operations on tolerations

---

pkg/utils/common.go
pkg/utils/validator/membercluster.go
pkg/utils/validator/membercluster_test.go
pkg/webhook/add_handler.go
pkg/webhook/clusterresourceplacement/v1alpha1_clusterresourceplacement_validating_webhook.go
pkg/webhook/clusterresourceplacement/v1beta1_clusterresourceplacement_validating_webhook.go
pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook.go
pkg/webhook/membercluster/membercluster_validating_webhook.go
pkg/webhook/pod/pod_validating_webhook.go
pkg/webhook/replicaset/replicaset_validating_webhook.go
pkg/webhook/webhook.go
pkg/webhook/webhook_test.go
test/e2e/webhook_test.go

feat: validate taints

---

apis/placement/v1beta1/binding_types.go
apis/placement/v1beta1/clusterresourceplacement_types.go
apis/placement/v1beta1/work_types.go
config/crd/bases/placement.kubernetes-fleet.io_clusterresourceplacements.yaml

Add api changes required by the advanced rollout
Fixes #
I have:
NA

interface: support advanced rollout

---

pkg/utils/validator/clusterresourceplacement.go
pkg/utils/validator/clusterresourceplacement_test.go

fix: remove check for tolerations, empty value, operator is equal

---

apis/placement/v1alpha1/common.go
apis/placement/v1alpha1/overridesnapshot_types.go
apis/placement/v1beta1/commons.go
pkg/controllers/overrider/clusterresource_controller.go
pkg/controllers/overrider/clusterresource_controller_integration_test.go
pkg/controllers/overrider/common.go
pkg/controllers/overrider/common_integration_test.go
pkg/controllers/overrider/common_test.go
pkg/controllers/overrider/resource_controller.go
pkg/controllers/overrider/suite_test.go
pkg/utils/common.go
pkg/utils/controller/controller.go
pkg/utils/labels/labels.go

The main code  logic for cluster resource override controller. Most of the code changes are related to refactoring the code to have a common code for CRO and RO.
Fixes #
I have:

feat: cluster resource override controller

---

apis/placement/v1beta1/clusterresourceplacement_types.go
apis/placement/v1beta1/policysnapshot_types.go
pkg/scheduler/framework/plugins/tainttoleration/filtering.go
pkg/scheduler/framework/plugins/tainttoleration/filtering_test.go
pkg/scheduler/framework/plugins/tainttoleration/plugin.go
pkg/utils/common.go
pkg/webhook/clusterresourceplacement/v1beta1_clusterresourceplacement_validating_webhook.go

Fixes #
I have:
UTs
ITs and E2Es will be added in separate PRs

feat: taints & toleration plugin

---

apis/placement/v1beta1/clusterresourceplacement_types.go
pkg/controllers/clusterresourceplacement/placement_conditions.go
pkg/utils/condition/condition.go

These basic utils will be called/tested in the future PR.
Fixes #
I have:

feat: add crp status utils

---

pkg/utils/validator/clusterresourceplacement.go
pkg/utils/validator/clusterresourceplacement_test.go
pkg/utils/validator/membercluster_test.go
test/e2e/webhook_test.go

feat: pickFixed toleration validation, refactor UTs

---

cmd/hubagent/workload/setup.go
pkg/controllers/rollout/controller.go
pkg/controllers/workgenerator/controller.go
pkg/metrics/metrics.go
pkg/scheduler/scheduler.go
test/e2e/README.md
test/scheduler/suite_test.go

Allow the users to setup more than one worker for the scheduler.
Fixes #
I have:

perf: increase the number of  scheduler workers

---

apis/placement/v1beta1/clusterresourceplacement_types.go
pkg/controllers/clusterresourceplacement/controller.go
pkg/controllers/clusterresourceplacement/controller_test.go
pkg/controllers/clusterresourceplacement/placement_conditions.go
pkg/controllers/clusterresourceplacement/placement_controllerv1alpha1.go
pkg/controllers/clusterresourceplacement/placement_status.go
pkg/controllers/clusterresourceplacement/placement_status_test.go
pkg/utils/condition/condition.go

feat: populate the crp status using new conditions

---

pkg/webhook/pod/pod_validating_webhook.go
pkg/webhook/replicaset/replicaset_validating_webhook.go

fix: add logs for pod, replica set validating webhooks

---

apis/placement/v1alpha1/common.go
pkg/controllers/overrider/clusterresource_controller.go
pkg/controllers/overrider/clusterresource_controller_integration_test.go
pkg/controllers/overrider/common.go
pkg/controllers/overrider/common_test.go
pkg/controllers/overrider/resource_controller.go
pkg/controllers/overrider/resource_controller_integration_test.go
pkg/controllers/overrider/suite_test.go

Added the resource overrider controller test and fix the controller
Fixes #
I have:

test: add resource overrider test and fix bugs

---

pkg/scheduler/profile/profile.go
test/e2e/scheduler_watchers_test.go
test/e2e/setup_test.go
test/e2e/taint_toleration_test.go
test/e2e/utils_test.go

test: E2E for taint & toleration plugin

---

charts/hub-agent/crdbases/placement.kubernetes-fleet.io_clusterresourceoverrides.yaml
charts/hub-agent/crdbases/placement.kubernetes-fleet.io_resourceoverrides.yaml
charts/hub-agent/templates/crds/placement.kubernetes-fleet.io_clusterresourceoverrides.yaml
charts/hub-agent/templates/crds/placement.kubernetes-fleet.io_resourceoverrides.yaml
cmd/hubagent/main.go
pkg/controllers/rollout/controller.go
pkg/controllers/rollout/controller_test.go
pkg/controllers/rollout/override.go
pkg/controllers/rollout/override_test.go
pkg/controllers/rollout/suite_test.go

The bindings is out of date if the resourcesnapshot and their overrides are not latest.
Fixes #
I have:
UT tests, need to add ITs.

feat: rollout controller supports override

---

pkg/utils/validator/clusterresourceplacement.go
pkg/utils/validator/clusterresourceplacement_test.go

feat: update crp webhook to validate the applyStrategy field

---

pkg/utils/validator/clusterresourceoverride.go
pkg/utils/validator/clusterresourceoverride_test.go
pkg/webhook/clusterresourceoverride/clusterresourceoverride_validating_webhook.go

feat: cluster resource override validator functions

---

apis/placement/v1beta1/clusterresourceplacement_types.go
config/crd/bases/placement.kubernetes-fleet.io_clusterresourcebindings.yaml
config/crd/bases/placement.kubernetes-fleet.io_clusterresourceplacements.yaml
config/crd/bases/placement.kubernetes-fleet.io_works.yaml
pkg/utils/validator/clusterresourceplacement_test.go

Fixes #
I have:
Since the current default behavior is client side apply + fail if co-own, add a new field called "allowCoOwnership" so that the default value is false.

interface: update apply strategy to call out allowing co-ownership explicitly

---

pkg/controllers/workgenerator/controller.go
pkg/controllers/workgenerator/controller_integration_test.go
pkg/controllers/workgenerator/controller_test.go
test/e2e/setup_test.go

mark binding as available according to the work
Fixes #
I have:

feat: mark binding as available according to the work

---

pkg/utils/validator/resourceoverride.go
pkg/utils/validator/resourceoverride_test.go
pkg/webhook/resourceoverride/resourceoverride_validating_webhook.go

feat: resource override validator functions

---

pkg/propertyprovider/aks/controllers/node.go
pkg/propertyprovider/aks/controllers/pod.go
pkg/propertyprovider/aks/provider.go
pkg/propertyprovider/aks/provider_integration_test.go
pkg/propertyprovider/aks/provider_test.go
pkg/propertyprovider/aks/suite_test.go
pkg/propertyprovider/aks/trackers/nodes.go
pkg/propertyprovider/aks/trackers/pods.go
pkg/propertyprovider/interface.go

This PR adds the AKS property provider implementation.
I have:
Some tests are removed from this PR to control its size; will submit a new PR to add them back.

feat: property-based scheduling: add AKS property provider

---

pkg/controllers/workgenerator/controller.go
pkg/controllers/workgenerator/controller_integration_test.go

add work created condition in the binding. We will remove the bound condition later.
Fixes #
I have:

feat: add work created condition in the binding

---

pkg/utils/validator/clusterresourceoverride.go
pkg/utils/validator/clusterresourceoverride_test.go
pkg/utils/validator/resourceoverride.go
pkg/utils/validator/resourceoverride_test.go

feat: add validation for cluster selector for override rule

---

hack/Azure/setup/README.md
hack/Azure/setup/createHubCluster.sh
hack/Azure/setup/joinMC.sh

Hub cluster setup and member cluster joining scripts.
Fixes #
I have:

docs: fleet setup scripts

---

pkg/utils/validator/clusterresourceplacement.go
pkg/utils/validator/clusterresourceplacement_test.go

feat: add property based scheduling validation to clusterresourceplacement webhook

---

pkg/scheduler/watchers/membercluster/controller_integration_test.go
pkg/scheduler/watchers/membercluster/watcher.go
test/e2e/taint_toleration_test.go
test/scheduler/tainttoleration_integration_test.go

Fixes #
I have:
The PR is to trigger a scheduling cycle when a taint is updated/deleted on a MC so that CRPs with pickAll, pickN placement policies can pick cluster

feat: watch MC taint update/delete

---

pkg/controllers/rollout/controller.go
pkg/controllers/rollout/controller_integration_test.go
pkg/controllers/rollout/controller_test.go
pkg/controllers/work/apply_controller.go
pkg/controllers/work/apply_controller_integration_test.go
pkg/controllers/work/apply_controller_test.go

Use the avail condition instead of applied
Fixes #
I have:
UT

feat: check ready status by using avail condition

---

apis/placement/v1beta1/binding_types.go
apis/placement/v1beta1/clusterresourceplacement_types.go
pkg/controllers/clusterresourcebindingwatcher/watcher_integration_test.go
pkg/controllers/clusterresourceplacement/controller_test.go
pkg/controllers/clusterresourceplacement/placement_status.go
pkg/controllers/clusterresourceplacement/placement_status_test.go
pkg/controllers/workgenerator/controller.go
pkg/controllers/workgenerator/controller_integration_test.go
pkg/utils/condition/condition.go

Rename workCreated to workSynchronized
Fixes #
I have:

feat: rename crp conditions

---

pkg/controllers/workgenerator/controller.go
pkg/controllers/workgenerator/controller_test.go

rollout controller depends on this reason to decide whether to wait or not
Fixes #
I have:
UT

fix: set notTrackable reason for the binding

---

pkg/controllers/rollout/controller.go
pkg/controllers/rollout/controller_test.go

Rollout controller needs to update the rolloutStarted condition if there is no binding to rollout
Fixes #
I have:

fix: reconcile the binding status

---

test/e2e/placement_selecting_resources_test.go

Fixes #
I have: 
- change the name so of the cluster scoped resource so it doesn’t conflict with another 
- Fixed the eventually function variable 
- Ensure the correct namespace is called

fix: fix flaky e2e tests

---

pkg/controllers/workgenerator/controller.go

This PR helps reduce write conflicts to improve the overall performance.
For more information, see the Performance Boost Exploration report.
I have:
N/A

perf: avoid write conflicts to improve work generator performance under heavy workload

---

docs/getting-started/README.md

This PR adds the TOC for the getting started docs.
I have:
N/A
N/A

docs: add TOC for the getting started docs

---

docs/concepts/ClusterResourcePlacement/README.md
docs/concepts/MemberCluster/README.md
docs/concepts/Scheduling-Framework/README.md
docs/howtos/taint-toleration.md

docs: concepts, how-to guide for taints & tolerations

---

apis/placement/v1beta1/binding_types.go
cmd/hubagent/workload/setup.go
go.mod
pkg/controllers/clusterresourceplacement/controller.go
pkg/controllers/clusterresourceplacement/controller_integration_test.go
pkg/controllers/clusterresourceplacement/controller_test.go
pkg/controllers/clusterresourceplacement/placement_controllerv1alpha1.go
pkg/controllers/clusterresourceplacement/placement_status.go
pkg/controllers/clusterresourceplacement/placement_status_test.go
pkg/controllers/clusterresourceplacement/suite_test.go
pkg/controllers/overrider/clusterresource_controller.go
pkg/controllers/rollout/controller.go
pkg/controllers/workgenerator/controller.go
pkg/controllers/workgenerator/controller_integration_test.go
pkg/controllers/workgenerator/controller_test.go
pkg/utils/condition/condition.go
test/e2e/actuals_test.go
test/e2e/enveloped_object_placement_test.go
test/e2e/placement_pickall_test.go
test/e2e/placement_pickfixed_test.go
test/e2e/placement_pickn_test.go
test/e2e/placement_selecting_resources_test.go
test/e2e/rollout_test.go
test/e2e/scheduler_watchers_test.go
test/e2e/setup.sh
test/e2e/taint_toleration_test.go
test/e2e/utils_test.go

feat: enabling the new condition

---

test/e2e/actuals_test.go
test/e2e/placement_cro_test.go
test/e2e/placement_ro_test.go
test/e2e/placement_selecting_resources_test.go
test/e2e/resources_test.go
test/e2e/setup_test.go
test/e2e/utils_test.go

Add override test
Fixes #
I have:

test: add override basic e2e test

---

apis/placement/v1/binding_types.go
apis/placement/v1/clusterresourceplacement_types.go
config/crd/bases/placement.kubernetes-fleet.io_clusterresourceplacements.yaml

fix the v1 api comment
Fixes #
I have:

fix: fix the v1 api comment

---

apis/placement/v1/binding_types.go
apis/placement/v1/work_types.go
config/crd/bases/placement.kubernetes-fleet.io_clusterresourcebindings.yaml
config/crd/bases/placement.kubernetes-fleet.io_works.yaml

update internal object comment
Fixes #
I have:

fix: fix v1 api comment

---

pkg/controllers/workgenerator/controller.go
pkg/controllers/workgenerator/controller_integration_test.go
test/e2e/actuals_test.go
test/e2e/enveloped_object_placement_test.go
test/e2e/placement_apply_strategy_test.go
test/e2e/placement_cro_test.go
test/e2e/placement_ro_test.go
test/e2e/placement_selecting_resources_test.go
test/e2e/resources_test.go
test/e2e/setup.sh
test/e2e/utils_test.go

fix: add apply strategy in work

---

examples/test-cro1.yaml
examples/test-crp2.yaml
examples/test-crp3.yaml
examples/test-crp4.yaml
examples/test-crp5.yaml
examples/test-crp6.yaml
examples/test-crp7.yaml
examples/test-crp8.yaml
examples/test-ro1.yaml

docs: example CRP & override files

---

cmd/hubagent/workload/setup.go
test/e2e/placement_cro_test.go
test/e2e/placement_ro_test.go

This PR has the override controllers disabled for debugging purposes.
I have:
N/A

fix: disable override controllers for debugging purposes

---

cmd/hubagent/workload/setup.go
test/e2e/placement_cro_test.go
test/e2e/placement_ro_test.go

This PR enables the override controllers and adds the CRD presence checks for the related CRDs.
I have:

fix: re-enable override controllers + add necessary CRD checks

---

apis/placement/v1/clusterresourceplacement_types.go
apis/placement/v1beta1/clusterresourceplacement_types.go
config/crd/bases/placement.kubernetes-fleet.io_clusterresourceplacements.yaml

support the advanced rollout
Fixes #
I have:
manual test,
kubectl get crp
NAME    GEN   SCHEDULED   SCHEDULEDGEN   AVAILABLE   AVAILABLEGEN   AGE
crp-1   1     True        1              True        1              87m

fix: show available condition instead of applied in kubectl

---

examples/test-crp1.yaml

Fixes #
I have: add a crp example to using property selector

docs: add propertySelector crp example

---

test/e2e/placement_cro_test.go
test/e2e/placement_ro_test.go

to fix the master branch
Fixes #
I have:

fix: remove duplicate import

---

docs/concepts/PropertyProviderAndClusterProperties/README.md

This PR adds a concept documentation piece for property-based scheduling.
I have:
N/A
N/A

docs: add property-based scheduling concept docs

---

hack/aks/property-based-scheduling.md

This PR adds the guide for using the new property-based scheduling feature. This is to help the audience in the upcoming KubeCon to try the new feature out. 
I have:
N/A
N/A

docs: add the guide for using the new property-based scheduling feature

---

test/e2e/placement_pickall_test.go
test/e2e/placement_selecting_resources_test.go
test/e2e/taint_toleration_test.go

Fixes #
I have: ensured resources that are being created for a test are being deleted to no conflict with other tests.

fix: fix flaky e2e tests - ensure resources are being deleted

---

pkg/utils/validator/clusterresourceplacement.go
pkg/utils/validator/clusterresourceplacement_test.go

fix: add validation to ensure unique cluster names for pickFixed CRP

---

.github/workflows/ci.yml
.github/workflows/code-lint.yml
.golangci.yml
Makefile
docker/hub-agent.Dockerfile
docker/member-agent.Dockerfile
docker/refresh-token.Dockerfile
go.mod

scan image failed
https://github.com/Azure/fleet/actions/runs/8997697599/job/24716356414
hubagent (gobinary)
===================
Total: 1 (HIGH: 1, CRITICAL: 0)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬────────────────┬────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version  │                       Title                        │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼────────────────┼────────────────────────────────────────────────────┤
│ stdlib  │ CVE-2023-[45](https://github.com/Azure/fleet/actions/runs/8997697599/job/24716356414#step:8:46)288 │ HIGH     │ fixed  │ 1.20.14           │ 1.21.9, 1.22.2 │ golang: net/http, x/net/http2: unlimited number of …

fix: upgrade golang version to 1.22.2 for CVE-2023-45288

---

docs/concepts/Override/README.md

docs: add override concept doc

---

docs/howtos/README.md
docs/howtos/cluster-resource-override.md
docs/howtos/resource-override.md

docs: how to docs for overrides

---

.github/workflows/ci.yml
pkg/controllers/work/apply_controller.go
pkg/controllers/work/apply_controller_integration_test.go
pkg/controllers/work/apply_controller_test.go
pkg/utils/common.go
test/e2e/actuals_test.go
test/e2e/enveloped_object_placement_test.go
test/e2e/placement_apply_strategy_test.go
test/e2e/placement_pickall_test.go
test/e2e/placement_pickfixed_test.go
test/e2e/placement_pickn_test.go
test/e2e/placement_selecting_resources_test.go
test/e2e/rollout_test.go
test/e2e/scheduler_watchers_test.go
test/e2e/setup_test.go
test/e2e/taint_toleration_test.go
test/e2e/utils_test.go
test/e2e/v1alpha1/utils/helper.go
test/e2e/webhook_test.go

Mark resources that mostly just contains data as available as there 
Fixes #
I have:
UT/E2E/IT

feat: make data resources available

---

pkg/scheduler/framework/framework.go
pkg/scheduler/framework/framework_test.go
pkg/scheduler/framework/frameworkutils.go

Fixes #
I have: updated scheduler message to include number of clusters

fix: update scheduler message

---

pkg/utils/validator/clusterresourceplacement.go
pkg/utils/validator/clusterresourceplacement_test.go

feat: add validation for property sort order

---

.github/workflows/ci.yml
.github/workflows/code-lint.yml
.golangci.yml
docker/hub-agent.Dockerfile
docker/member-agent.Dockerfile
docker/refresh-token.Dockerfile
go.mod

fix the workflow failure, https://github.com/Azure/fleet/actions/runs/9038604706/job/24840052636
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬───────────────┬────────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version │                           Title                            │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼───────────────┼────────────────────────────────────────────────────────────┤
│ stdlib  │ CVE-2024-2[47](https://github.com/Azure/fleet/actions/runs/9038604706/job/24840052636#step:8:48)88 │ HIGH     │ fixed  │ 1.22.2            │ 1.22.3        │ golang: net: malformed DNS message can cause infinite loop │
│         │                │ …

fix: upgrade go version to 1.22.3 for CVE-2024-24788

---

docs/concepts/PropertyProviderAndClusterProperties/README.md

docs: remove preview tag

---

docs/concepts/README.md

docs: fix the concept readme

---

hack/loadtest/util/placement.go

fix: fix the perf test

---

test/e2e/actuals_test.go
test/e2e/rollout_test.go
test/e2e/setup_test.go

test: safe rollout e2e deployment

---

hack/loadtest/main.go
hack/loadtest/util/help.go
hack/loadtest/util/placement.go

test: update perf test to print results

---

test/e2e/placement_cro_test.go
test/e2e/placement_ro_test.go
test/e2e/scheduler_watchers_test.go

Fixes #
I have: update newly merged e2e with new changes. 
Currently is blocking PR's because causing e2e to fail.

fix: fix property based scheduling e2e

---

test/e2e/actuals_test.go
test/e2e/placement_cro_test.go
test/e2e/placement_ro_test.go
test/e2e/utils_test.go

test: add more override e2e tests

---

docs/concepts/ClusterResourcePlacement/README.md
docs/concepts/MemberCluster/README.md

docs: add formal definition for taints & tolerations

---

pkg/controllers/internalmembercluster/v1beta1/member_controller.go
pkg/controllers/internalmembercluster/v1beta1/member_controller_test.go

This PR addresses a bug in the IMC resource stats collection process. It also adds the unit test for the affected method.
I have:
IMC controller tests are being refactored; more PRs will ensue.

fix: address a bug in the IMC resource stats collection process + add corresponding unit test

---

test/e2e/placement_apply_strategy_test.go

Add more server-side apply test cases
Fixes #
I have:

test: add server-side apply e2e test

---

apis/placement/v1/clusterresourceplacement_types.go
apis/placement/v1beta1/clusterresourceplacement_types.go
config/crd/bases/placement.kubernetes-fleet.io_clusterresourceplacements.yaml
docs/concepts/README.md
docs/concepts/SafeRollout/README.md

We need to spell out the rollout strategy more clearly
Fixes #
I have:

docs:  rollout concept doc

---

pkg/scheduler/framework/framework.go
pkg/scheduler/framework/framework_test.go
pkg/scheduler/framework/frameworkutils.go

Fixes #
I have: capitalize message and label as template
Addresses comments on #825

fix: fix message

---

go.mod
test/e2e/placement_selecting_resources_test.go

downgrade the go mod so others can import it
Fixes #
I have:

fix: downgrade go mod

---

go.mod
pkg/propertyprovider/azure/trackers/nodes.go

bump the log level
Fixes #
I have:

fix: bump the log level to show in prod

---

pkg/controllers/work/apply_controller_integration_test.go

Fix the integration flakiness.
build failure
https://github.com/Azure/fleet/actions/runs/9277989393/job/25528229224
Fixes #
I have:

fix: fix apply work controller integration test

---

pkg/utils/validator/clusterresourceplacement.go
pkg/utils/validator/clusterresourceplacement_test.go

fix: flaky UT for property name validation

---

test/e2e/placement_pickfixed_test.go

fix: flaky E2E add retry for update

---

pkg/controllers/workgenerator/override.go

Fixes #
I have: Make sure the correct corresponding override map is being logged.

fix: fix override log

---

pkg/utils/common.go
test/e2e/actuals_test.go
test/e2e/enveloped_object_placement_test.go
test/e2e/rollout_test.go
test/e2e/taint_toleration_test.go

test: safe rollout E2E service

---

.github/workflows/ci.yml
.github/workflows/code-lint.yml
.github/workflows/trivy.yml
.golangci.yml
docker/hub-agent.Dockerfile
docker/member-agent.Dockerfile
docker/refresh-token.Dockerfile

https://github.com/Azure/fleet/actions/runs/9574800698/job/26398647455
Fix CVE-2024-24790
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬─────────────────┬────────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │  Fixed Version  │                           Title                            │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼─────────────────┼────────────────────────────────────────────────────────────┤
│ stdlib  │ CVE-2024-2[47](https://github.com/Azure/fleet/actions/runs/9574800698/job/26398647455#step:8:48)90 │ CRITICAL │ fixed  │ 1.22.3            │ 1.21.11, 1.22.4 │ golang: net/netip: Unexpected behavior from Is methods for │
│         │                │ …

chore: upgrade go version to 1.22.4

---

docs/concepts/SafeRollout/README.md
pkg/controllers/work/apply_controller.go
pkg/controllers/work/apply_controller_test.go

feat: remove job availability tracking

---

cmd/memberagent/main.go

fix: check for appliedWork CRD in fleet-member-agent

---

apis/placement/v1beta1/clusterresourceplacement_types.go
config/crd/bases/placement.kubernetes-fleet.io_clusterresourceplacements.yaml

docs: Update API doc for CRP regarding job availability tracking

---

apis/placement/v1/clusterresourceplacement_types.go
config/crd/bases/placement.kubernetes-fleet.io_clusterresourceplacements.yaml

docs: update v1 CRP API doc

---

pkg/controllers/workgenerator/controller_test.go

Fix the unit test failure
https://github.com/Azure/fleet/actions/runs/9601760461/attempts/1
Fixes #
I have:

fix: fix ut flakiness

---

pkg/utils/common.go
test/e2e/resources/test-job.yaml
test/e2e/rollout_test.go

Fixes #
I have:
Opened PR to address this comment https://github.com/Azure/fleet/pull/860#pullrequestreview-2133263806.

test: e2e of Job Rollout, doesn't block

---

pkg/controllers/workgenerator/controller_test.go

Need to reset the maxFailedResourcePlacementLimit for each test case
Fixes #
I have:

fix: fix the SetBindingStatus unit test

---

pkg/utils/controller/controller.go

Add the stack trace for the unexpected error
Fixes #
I have:

fix: print stack trace for the unexpected error

---

apis/cluster/v1/membercluster_types.go
apis/cluster/v1beta1/membercluster_types.go
config/crd/bases/cluster.kubernetes-fleet.io_memberclusters.yaml

feat: change print column name for member agent HB

---

pkg/controllers/internalmembercluster/v1beta1/member_controller.go
pkg/utils/controller/controller.go

create a common interface for member controller so that imc controller can start/stop any controller.
Fixes #
I have:

feat: create an interface for member controller

---

examples/ngnix/config-ro.yaml
examples/ngnix/configMap.yaml
examples/ngnix/deployment.yaml
examples/ngnix/namespace.yaml
examples/ngnix/place-all-crp.yaml
examples/ngnix/service.yaml

an example with nginx homepage override by region
Fixes #
I have:

docs: add an example with nginx homepage override by region

---

docs/tutorials/ClusterMigrationDR.md
docs/tutorials/MigrationWithOverrideDR.md
docs/tutorials/README.md
docs/tutorials/RegionMigrationDR.md

Add tutorials for stateless application. Scenarios:
- Move application from region to region
- Move application from cluster to cluster while scaling up
Fixes #
I have:

docs: add tutorials

---

docs/concepts/SafeRollout/README.md

minor change to the doc, mimic https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#health-checks
Fixes #
I have:

docs: Update README.md

---

test/scheduler/actuals_test.go
test/scheduler/pickn_integration_test.go
test/scheduler/tainttoleration_integration_test.go

This PR fixes a issue that under extremely rare cases would lead to test failures in the scheduler integration tests.
I have:
N/A
N/A

fix: address a rare case that might lead to scheduler integration test flakiness

---

pkg/scheduler/framework/plugins/clusteraffinity/filtering_test.go
pkg/scheduler/framework/plugins/clusteraffinity/types.go
pkg/scheduler/framework/plugins/clusteraffinity/types_test.go

This PR adds some UTs for the cluster affinity scheduler plugin.
I have:
N/A
N/A

test: add additional unit tests for cluster affinity scheduler plugin

---

hack/Azure/setup/README.md
hack/Azure/setup/createHubCluster.sh
hack/Azure/setup/joinMC.sh

Fixes #
I have:
Manually ran the script to join 2 member clusters to a fleet hub

feat: minor changes to Azure joinMC script

---

docs/troubleshooting/README.md
docs/troubleshooting/clusterResourcePlacementApplied.md
docs/troubleshooting/clusterResourcePlacementAvailable.md
docs/troubleshooting/clusterResourcePlacementOverridden.md
docs/troubleshooting/clusterResourcePlacementRolloutStarted.md
docs/troubleshooting/clusterResourcePlacementScheduled.md
docs/troubleshooting/clusterResourcePlacementWorkSynchronized.md

docs: update tsg

---

.github/workflows/ci.yml
docker/hub-agent.Dockerfile
docker/member-agent.Dockerfile
docker/refresh-token.Dockerfile
go.mod
go.sum
pkg/controllers/workgenerator/controller.go

fix: minor fix for CI

---

charts/hub-agent/templates/deployment.yaml
charts/hub-agent/values.yaml
cmd/hubagent/main.go
cmd/hubagent/options/options.go
pkg/controllers/membercluster/v1beta1/membercluster_controller.go
pkg/controllers/membercluster/v1beta1/membercluster_controller_integration_test.go
test/e2e/join_and_leave_test.go
test/e2e/setup.sh
test/e2e/setup_test.go
test/e2e/utils_test.go

feat: force delete member cluster

---

test/e2e/join_and_leave_test.go

Fixes #
I have:
PR was opened to address this comment https://github.com/Azure/fleet/pull/905#discussion_r1732113048

test: force delete E2E add check to ensure pods match replicas

---

apis/placement/v1/binding_types.go
apis/placement/v1beta1/binding_types.go
pkg/controllers/clusterresourcebindingwatcher/watcher.go
pkg/controllers/workgenerator/controller.go
pkg/controllers/workgenerator/controller_integration_test.go
pkg/controllers/workgenerator/controller_test.go
pkg/controllers/workgenerator/override_test.go
test/e2e/rollout_test.go
test/e2e/setup_test.go
test/e2e/utils_test.go

Fixes #
I have: implemented some fixes so that the binding transition times updates for available condition, as well as add a retry for when there is a conflict when updating the binding.

fix: updates binding transition times

---

apis/placement/v1beta1/clusterresourceplacement_types.go
config/crd/bases/placement.kubernetes-fleet.io_clusterresourcebindings.yaml
config/crd/bases/placement.kubernetes-fleet.io_clusterresourceplacements.yaml
config/crd/bases/placement.kubernetes-fleet.io_works.yaml

Per requests from the customer side, this PR adds a new apply strategy. It also clarifies the differences between strategies in the comments.
I have:
N/A

interface: add additional apply strategy

---

apis/placement/v1beta1/clusterresourceplacement_types.go
config/crd/bases/placement.kubernetes-fleet.io_approvalrequests.yaml
config/crd/bases/placement.kubernetes-fleet.io_clusterresourcebindings.yaml
config/crd/bases/placement.kubernetes-fleet.io_clusterresourceplacements.yaml
config/crd/bases/placement.kubernetes-fleet.io_stagedupdateruns.yaml
config/crd/bases/placement.kubernetes-fleet.io_stagedupdatestrategies.yaml
config/crd/bases/placement.kubernetes-fleet.io_works.yaml
pkg/scheduler/framework/framework.go
test/scheduler/pickn_integration_test.go

This PR fixes some spelling errors in the code/manifests.
I have:
N/A
N/A

fix: some spelling errors + re-gen the manifests

---

apis/placement/v1alpha1/disruptionbudget_types.go
config/crd/bases/placement.kubernetes-fleet.io_clusterresourceplacementdisruptionbudgets.yaml

fix: remove status marker from CRPDB API

---

charts/hub-agent/templates/crds/placement.kubernetes-fleet.io_clusterapprovalrequests.yaml
charts/hub-agent/templates/crds/placement.kubernetes-fleet.io_clusterresourceplacementdisruptionbudgets.yaml
charts/hub-agent/templates/crds/placement.kubernetes-fleet.io_clusterresourceplacementevictions.yaml
charts/hub-agent/templates/crds/placement.kubernetes-fleet.io_clusterstagedupdateruns.yaml
charts/hub-agent/templates/crds/placement.kubernetes-fleet.io_clusterstagedupdatestrategies.yaml

This PR adds soft links to the test env. charts that connects to the new API.
I have:
N/A
N/A

test: add new APIs to the test environment charts

---

apis/placement/v1beta1/clusterresourceplacement_types.go

This PR fixes a minor inconsistency of constant values in the API package.
I have:
N/A

fix: minor constant value change in the API package

---

examples/eviction/clusterpdb.yaml
examples/eviction/eviction.yaml
examples/eviction/test-crp.yaml
examples/migration/crp-1.yaml
examples/migration/crp-2.yaml
examples/migration/resourceoverride.yaml
examples/stagedupdaterun/approvalRequest.yaml
examples/stagedupdaterun/clusterStagedUpdateRun.yaml
examples/stagedupdaterun/example-crp.yaml
examples/stagedupdaterun/updateStrategy.yaml

docs: add more demo example yamls

---

Makefile

Fixes #
I have:
Successful CI pipeline run https://github.com/Azure/fleet/actions/runs/12015848213/job/33494784150?pr=971

fix: add test/apis directory for running test in makefile

---

test/apis/cluster/v1beta1/api_validation_integration_test.go
test/apis/cluster/v1beta1/suite_test.go

Add integration tests for v1beta1 mc
Fixes #
I have:

test: create v1beta1 tests

---

pkg/controllers/workgenerator/controller.go
pkg/controllers/workgenerator/controller_test.go

Fixes #
I have: sort drift/diff placement when overflow and fix SetBindingStatus UT

fix: fix SetBindingStatus UT

---

apis/placement/v1beta1/eviction_types.go
config/crd/bases/placement.kubernetes-fleet.io_clusterresourceplacementevictions.yaml

Invalid eviction:
Valid & Executed eviction:
Valid but not executed eviction:
Fixes #
I have:

feat: add print columns for CRP eviction

---

README.md
SUPPORT.md

docs: Minor fix on the readme

---

cmd/hubagent/options/options.go

Enable StagedUpdateRun feature.
Fixes #
I have:

feat: enable staged update run controller by default

---

test/e2e/placement_pickn_test.go
test/e2e/updaterun_test.go

1. fix update run e2e logic
2. fix the long wait between stages when we are just waiting for the wait task
Fixes #
I have:

fix: fix update run e2e and code

---

cmd/hubagent/options/options.go

feat: enable eviction controller by default

---

pkg/controllers/workapplier/controller.go
pkg/controllers/workapplier/status.go

This PR adds some minor fixes to the new work applier in response to the left-over comments on #1039.
I have:
N/A

fix: address left-over comments in prev. PR

---

cmd/hubagent/workload/setup.go

Fix a bug found when v1alpha1 updateRun APIs are unserved.
Fixes #
I have:
Run e2e tests locally with v1alpha1 APIs disabled.

fix: fix updaterun version check

---

test/e2e/rollout_test.go

This PR fixes a flaky test spec in the rollout controller E2E test suite.
I have:
N/A
N/A

test: fix a flaky test spec in the rollout controller E2E test suite

---

pkg/controllers/rollout/controller.go
test/e2e/actuals_test.go
test/e2e/placement_cro_test.go
test/e2e/placement_ro_test.go

fix: handle override delete on demand

---

examples/kueue/cluster-queue.yaml
examples/kueue/create_jobs.sh
examples/kueue/flavors.yaml
examples/kueue/job-team-a.yaml
examples/kueue/job-team-b.yaml
examples/kueue/local-queue.yaml
examples/kueue/team-a-crp.yaml
examples/kueue/team-b-crp.yaml

This is the multi-cluster version of the https://cloud.google.com/kubernetes-engine/docs/tutorials/kueue-intro
Fixes #
I have:

docs: queue example

---

.github/workflows/upgrade.yml

This PR updates the GitHub Actions spec for the Fleet agent upgrade scenario to:
a) use the correct flow name
b) allow input parameters
I have:
N/A

test: tweak the upgrade GitHub Actions spec

---

cmd/hubagent/options/options.go

enable clusterProfile api by default
Fixes #
I have:

feat: enable clusterProfileapi

---

pkg/controllers/clusterresourceplacementeviction/controller.go
pkg/utils/controller/metrics/metrics.go

feat: CRP Eviction completion metric

---

pkg/controllers/workapplier/availability_tracker.go
pkg/controllers/workapplier/availability_tracker_test.go

Fixes #
I have: addressed comments from #1061

fix: minor fixes to ServiceExport Trackability

---

test/e2e/placement_eviction_test.go

test: increase timeout for specific eviction E2E

---

docs/howtos/reportdiff.md

docs: update reportDiff howto to use new condition

---

.github/workflows/ci.yml
.github/workflows/code-lint.yml
.github/workflows/trivy.yml
.github/workflows/upgrade.yml
.golangci.yml
docker/hub-agent.Dockerfile
docker/member-agent.Dockerfile
docker/refresh-token.Dockerfile
go.mod

fix cve
hubagent (gobinary)
===================
Total: 1 (HIGH: 1, CRITICAL: 0)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬────────────────┬───────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version  │                           Title                           │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼────────────────┼───────────────────────────────────────────────────────────┤
│ stdlib  │ CVE-2024-34156 │ HIGH     │ fixed  │ v1.23.0           │ 1.22.7, 1.23.1 │ encoding/gob: golang: Calling Decoder.Decode on a message │
│         │                │          │        │                   │                │ which contains deeply nested structures... …

fix: bump go to 1.23.1

---

pkg/controllers/workapplier/status.go

Just fixes simple grammatical error in log message for applying work.

Fixed grammatical error in log message.

---

test/e2e/placement_selecting_resources_test.go

Experimental; will not be executed.
I have:
N/A
N/A

feat: experimental merge ops

---

pkg/controllers/updaterun/controller.go
pkg/controllers/updaterun/controller_integration_test.go
pkg/controllers/updaterun/execution.go
pkg/controllers/updaterun/execution_integration_test.go
pkg/controllers/updaterun/initialization_integration_test.go
pkg/controllers/updaterun/validation_integration_test.go
pkg/utils/condition/condition.go
pkg/utils/controller/metrics/metrics.go

chore: backport from kubefleet

---

README.md

fix the README to clarify its purpose
Fixes #
I have:

docs: fix the README

---

.github/workflows/build-publish-mcr.yml

chore: update publish MCR action to build, publish crd installer image

---

test/upgrade/setup.sh
test/upgrade/upgrade.sh

Disable the resourceSnapshot improvement features when running the compatibility tests to shorten the test time.
Fixes #
I have:

fix: disable the new features when running compatibility tests

---

charts/member-agent-arc/values.yaml

fix: Fix crdinstaller repository typo in member-agent-arc chart
Fixes #
I have:

fix: Fix crdinstaller repository typo in member-agent-arc chart

---

charts/member-agent-arc/templates/deployment.yaml

This PR fixes indentation in the arc agent deployment for custom cert.
Fixes #
I have:

fix: update indentation for custom cert
